/*GTCEuStartupEvents.registry("gtceu:recipe_type", event => {
        event.create("applied_enigma")
        .category("applied_assemblery")
        .setEUIO("in")
        .setMaxIOSize(8, 2, 2, 0)
        .setSlotOverlay(false, false, GuiTextures.CIRCUIT_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)

        event.create("hyperforming_press")
        .category("applied_assemblery")
        .setEUIO("in")
        .setMaxIOSize(6, 2, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.SLOT_DARK)
        .setProgressBar(GuiTextures.PROGRESS_BAR_COMPRESS, FillDirection.DOWN_TO_UP)
        .setSound(GTSoundEntries.ASSEMBLER)
})

GTCEuStartupEvents.registry("gtceu:machine", event => {
 event.create("applied_enigma", "multiblock")
    .rotationState(RotationState.NON_Y_AXIS)
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE])
        .recipeTypes([GTRecipeTypes.get('applied_enigma')])
        .appearanceBlock(() => Block.getBlock("gtceu:auralloy-omega_over_transcendentine_casing"))
        .pattern(definition => FactoryBlockPattern.start()
    .aisle("aaaabaaaa", "aaacbcaaa", "aaabbbaaa", "aacbcbcaa", "aabbbbbaa", "acbdddbca", "abbbbbbba", "abdddddba", "bbbbbbbbb", "bcccccccb", "bcdddddcb", "bcdddddcb", "bcccccccb", "bbbbbbbbb", "abdddddba", "abbbbbbba", "adbdddbda", "aabbbbbaa", "aacbcbcaa", "aaabbbaaa", "aaacbcaaa", "aaaabaaaa")
    .aisle("aaaabaaaa", "aaacecaaa", "aaabebaaa", "aaceeecaa", "aabeeebaa", "cceaaaecc", "bbeeeeebb", "beaaaaaeb", "beeeeeeeb", "ceeeeeeec", "ceaaaaaec", "ceaaaaaec", "ceeeeeeec", "beeeeeeeb", "beaaaaaeb", "bbeeeeebb", "ddaaaaadd", "aabeeebaa", "aaceeecaa", "aaabebaaa", "aaacecaaa", "aaaabaaaa")
    .aisle("aaaabaaaa", "aaacfcaaa", "aaabfbaaa", "cccfgfccc", "bbbfgfbbb", "befgfgfeb", "befgfgfeb", "dagfgfgad", "begfgfgeb", "ceggfggec", "daggfggad", "dagfgfgad", "cegfgfgec", "befgfgfeb", "dafgfgfad", "begfgfgeb", "bagfgfgab", "bbbgfgbbb", "cccgfgccc", "aaababaaa", "aaacacaaa", "aaaabaaaa")
    .aisle("aaaabaaaa", "ccccacccc", "bbbbabbbb", "befaaafeb", "befaaafeb", "dagaaagad", "begaaageb", "dafaaafad", "befaaafeb", "cegaaagec", "dagaaagad", "dafaaafad", "cefaaafec", "begaaageb", "dagaaagad", "befaaafeb", "dafaaafad", "begaaageb", "begaaageb", "bbbbabbbb", "ccccacccc", "aaaabaaaa")
    .aisle("bbbbbbbbb", "befahafeb", "befahafeb", "cegahagec", "begahageb", "dafahafad", "befahafeb", "dagahagad", "begahageb", "cefahafei", "dafahafad", "dagahagad", "cegahagec", "befahafeb", "dafahafad", "begahageb", "dagahagad", "befahafeb", "cefahafec", "beaahaaeb", "beaahaaeb", "bbbbbbbbb")
    .aisle("aaaabaaaa", "ccccacccc", "bbbbabbbb", "befaaafeb", "befaaafeb", "dagaaagad", "begaaageb", "dafaaafad", "befaaafeb", "cegaaagec", "dagaaagad", "dafaaafad", "cefaaafec", "begaaageb", "dagaaagad", "befaaafeb", "dafaaafad", "begaaageb", "begaaageb", "bbbbabbbb", "ccccacccc", "aaaabaaaa")
    .aisle("aaaabaaaa", "aaacfcaaa", "aaabfbaaa", "cccfgfccc", "bbbfgfbbb", "befgfgfeb", "befgfgfeb", "dagfgfgad", "begfgfgeb", "ceggfggec", "daggfggad", "dagfgfgad", "cegfgfgec", "befgfgfeb", "dafgfgfad", "begfgfgeb", "bagfgfgab", "bbbgfgbbb", "cccgfgccc", "aaababaaa", "aaacacaaa", "aaaabaaaa")
    .aisle("aaaabaaaa", "aaacecaaa", "aaabebaaa", "aaceeecaa", "aabeeebaa", "cceaaaecc", "bbeeeeebb", "beaaaaaeb", "beeeeeeeb", "ceeeeeeec", "ceaaaaaec", "ceaaaaaec", "ceeeeeeec", "beeeeeeeb", "beaaaaaeb", "bbeeeeebb", "ddaaaaadd", "aabeeebaa", "aaceeecaa", "aaabebaaa", "aaacecaaa", "aaaabaaaa")
    .aisle("aaaabaaaa", "aaacbcaaa", "aaabbbaaa", "aacbcbcaa", "aabbbbbaa", "acbdddbca", "abbbbbbba", "abdddddba", "bbbbbbbbb", "bcccccccb", "bcdddddcb", "bcdddddcb", "bcccccccb", "bbbbbbbbb", "abdddddba", "abbbbbbba", "adbdddbda", "aabbbbbaa", "aacbcbcaa", "aaabbbaaa", "aaacbcaaa", "aaaabaaaa")
    .where("a", Predicates.any())
    .where("b", Predicates.blocks("gtceu:echoing_fluxum_casing"))
    .where("c", Predicates.blocks("gtceu:auralloy-omega_over_transcendentine_casing")
        .or(Predicates.autoAbilities(definition.getRecipeTypes()))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
    .where("d", Predicates.blocks("ae2:quartz_vibrant_glass"))
    .where("e", Predicates.blocks("expatternprovider:assembler_matrix_frame"))
    .where("f", Predicates.blocks("gtceu:tungstensteel_gearbox"))
    .where("g", Predicates.blocks("gtceu:large_scale_assembler_casing"))
    .where("h", Predicates.blocks("gtceu:tungstensteel_pipe_casing"))
    .where("i", Predicates.controller(Predicates.blocks(definition.get())))
    .build())
    .workableCasingModel('gtceu:block/casings/solid/transcendentine_over_auralloy_casing', 'gtceu:block/machines/assembler')
})
*/

    