GTCEuStartupEvents.registry("gtceu:recipe_type", event => {
        event.create("applied_enigma")
        .category("applied_assemblery")
        .setEUIO("in")
        .setMaxIOSize(8, 2, 2, 0)
        .setSlotOverlay(false, false, GuiTextures.CIRCUIT_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_CIRCUIT_ASSEMBLER, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ASSEMBLER)

        event.create("hyperforming_press")
        .category("applied_assemblery")
        .setEUIO("in")
        .setMaxIOSize(6, 2, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.SLOT_DARK)
        .setProgressBar(GuiTextures.PROGRESS_BAR_COMPRESS, FillDirection.DOWN_TO_UP)
        .setSound(GTSoundEntries.ASSEMBLER)
})

GTCEuStartupEvents.registry("gtceu:machine", event => {
 event.create("applied_enigma", "multiblock")
    .rotationState(RotationState.NON_Y_AXIS)
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE])
        .recipeTypes([GTRecipeTypes.get('applied_enigma')])
        .appearanceBlock(() => Block.getBlock("gtceu:auralloy-omega_over_transcendentine_casing"))
        .pattern(definition => FactoryBlockPattern.start()
    .aisle("aaaabaaaa", "aaacbcaaa", "aaabbbaaa", "aacbcbcaa", "aabbbbbaa", "acbdddbca", "abbbbbbba", "abdddddba", "bbbbbbbbb", "bcccccccb", "bcdddddcb", "bcdddddcb", "bcccccccb", "bbbbbbbbb", "abdddddba", "abbbbbbba", "adbdddbda", "aabbbbbaa", "aacbcbcaa", "aaabbbaaa", "aaacbcaaa", "aaaabaaaa")
    .aisle("aaaabaaaa", "aaacacaaa", "aaababaaa", "aacaaacaa", "aabaaabaa", "ccaaaaacc", "bbaaaaabb", "baaaaaaab", "baaaaaaab", "caaaaaaac", "caaaaaaac", "caaaaaaac", "caaaaaaac", "baaaaaaab", "baaaaaaab", "bbaaaaabb", "ddaaaaadd", "aabaaabaa", "aacaaacaa", "aaababaaa", "aaacacaaa", "aaaabaaaa")
    .aisle("aaaabaaaa", "aaacacaaa", "aaababaaa", "cccaaaccc", "bbbaaabbb", "baaaaaaab", "baaaaaaab", "daaaaaaad", "baaaaaaab", "caaaaaaac", "daaaaaaad", "daaaaaaad", "caaaaaaac", "baaaaaaab", "daaaaaaad", "baaaaaaab", "baaaaaaab", "bbbaaabbb", "cccaaaccc", "aaababaaa", "aaacacaaa", "aaaabaaaa")
    .aisle("aaaabaaaa", "ccccacccc", "bbbbabbbb", "baaaaaaab", "baaaaaaab", "daaaaaaad", "baaaaaaab", "daaaaaaad", "baaaaaaab", "caaaaaaac", "daaaaaaad", "daaaaaaad", "caaaaaaac", "baaaaaaab", "daaaaaaad", "baaaaaaab", "daaaaaaad", "baaaaaaab", "baaaaaaab", "bbbbabbbb", "ccccacccc", "aaaabaaaa")
    .aisle("bbbbbbbbb", "baaaaaaab", "baaaaaaab", "caaaaaaac", "baaaaaaab", "daaaaaaad", "baaaaaaab", "daaaaaaad", "baaaaaaab", "caaaaaaac", "daaaaaaad", "daaaaaaad", "caaaaaaac", "baaaaaaab", "daaaaaaad", "baaaaaaab", "daaaaaaad", "baaaaaaab", "caaaaaaac", "baaaaaaab", "baaaaaaab", "bbbbbbbbb")
    .aisle("aaaabaaaa", "ccccacccc", "bbbbabbbb", "baaaaaaab", "baaaaaaab", "daaaaaaad", "baaaaaaab", "daaaaaaad", "baaaaaaab", "caaaaaaac", "daaaaaaad", "daaaaaaad", "caaaaaaac", "baaaaaaab", "daaaaaaad", "baaaaaaab", "daaaaaaad", "baaaaaaab", "baaaaaaab", "bbbbabbbb", "ccccacccc", "aaaabaaaa")
    .aisle("aaaabaaaa", "aaacacaaa", "aaababaaa", "cccaaaccc", "bbbaaabbb", "baaaaaaab", "baaaaaaab", "daaaaaaad", "baaaaaaab", "caaaaaaac", "daaaaaaad", "daaaaaaad", "caaaaaaac", "baaaaaaab", "daaaaaaad", "baaaaaaab", "baaaaaaab", "bbbaaabbb", "cccaaaccc", "aaababaaa", "aaacacaaa", "aaaabaaaa")
    .aisle("aaaabaaaa", "aaacacaaa", "aaababaaa", "aacaaacaa", "aabaaabaa", "ccaaaaacc", "bbaaaaabb", "baaaaaaab", "baaaaaaab", "caaaaaaac", "caaaaaaac", "caaaaaaac", "caaaaaaac", "baaaaaaab", "baaaaaaab", "bbaaaaabb", "ddaaaaadd", "aabaaabaa", "aacaaacaa", "aaababaaa", "aaacacaaa", "aaaabaaaa")
    .aisle("aaaabaaaa", "aaacbcaaa", "aaabbbaaa", "aacbcbcaa", "aabbbbbaa", "acbdddbca", "abbbbbbba", "abdddddba", "bbbbbbbbb", "bcccxcccb", "bcdddddcb", "bcdddddcb", "bcccccccb", "bbbbbbbbb", "abdddddba", "abbbbbbba", "adbdddbda", "aabbbbbaa", "aacbcbcaa", "aaabbbaaa", "aaacbcaaa", "aaaabaaaa")
    .where("a", Predicates.any())
    .where("b", Predicates.blocks("gtceu:echoing_fluxum_casing"))
    .where("e", Predicates.blocks("gtceu:large_scale_assembler_casing"))
    .where("d", Predicates.blocks("ae2:quartz_vibrant_glass"))
    .where("c", Predicates.blocks("gtceu:auralloy-omega_over_transcendentine_casing")
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
        .or(Predicates.autoAbilities(definition.getRecipeTypes())))
    .where("x", Predicates.controller(Predicates.blocks(definition.get())))
        .build())
    .workableCasingModel('gtceu:block/casings/solid/transcendentine_over_auralloy_casing', 'gtceu:block/machines/assembler')
})


    