GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
event.create('solar_collection')
.category('ree')
.setMaxIOSize(0, 0, 1, 4)
.setSlotOverlay(true, false, GuiTextures.VIAL_OVERLAY_1)
.setSlotOverlay(true, true, GuiTextures.VIAL_OVERLAY_2)
.setProgressBar(GuiTextures.PROGRESS_BAR_GAS_COLLECTOR, FillDirection.LEFT_TO_RIGHT)
.setSound(GTSoundEntries.COOLING)

event.create('lunar_collection')
.category('ree')
.setMaxIOSize(0, 0, 1, 4)
.setSlotOverlay(true, false, GuiTextures.VIAL_OVERLAY_1)
.setSlotOverlay(true, true, GuiTextures.VIAL_OVERLAY_2)
.setProgressBar(GuiTextures.PROGRESS_BAR_GAS_COLLECTOR, FillDirection.LEFT_TO_RIGHT)
.setSound(GTSoundEntries.COOLING)
})
GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('solar_collector', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes(GTRecipeTypes.get('solar_collection'))
    .appearanceBlock(() => Block.getBlock("gtceu:nitinol_casing"))
    .pattern(definition => FactoryBlockPattern.start()
.aisle("aaaaa", "bbbbb")
.aisle("accca", "bbbbb")
.aisle("accca", "bbbbb")
.aisle("accca", "bbbbb")
.aisle("aadaa", "bbbbb")
.where("a", Predicates.blocks("gtceu:nitinol_casing")
    .or(Predicates.autoAbilities(definition.getRecipeTypes()))
    .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
.where("b", Predicates.blocks("kubejs:lumium_glass"))
.where("c", Predicates.blocks("gtceu:lumium_solar_collector"))
.where("d", Predicates.controller(Predicates.blocks(definition.get())))
.build())
.workableCasingModel('gtceu:block/casings/solid/nitinol_casing', 
    'gtceu:block/machines/gas_collector')

    event.create('lunar_collector', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes(GTRecipeTypes.get('lunar_collection'))
    .appearanceBlock(() => Block.getBlock("gtceu:nitinol_casing"))
    .pattern(definition => FactoryBlockPattern.start()
.aisle("aaaaa", "bbbbb")
.aisle("accca", "bbbbb")
.aisle("accca", "bbbbb")
.aisle("accca", "bbbbb")
.aisle("aadaa", "bbbbb")
.where("a", Predicates.blocks("gtceu:nitinol_casing")
    .or(Predicates.autoAbilities(definition.getRecipeTypes()))
    .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
.where("b", Predicates.blocks("kubejs:enderium_glass"))
.where("c", Predicates.blocks("gtceu:enderium_lunar_collector"))
.where("d", Predicates.controller(Predicates.blocks(definition.get())))
.build())
.workableCasingModel('gtceu:block/casings/solid/nitinol_casing', 
    'gtceu:block/machines/gas_collector')
})