GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
event.create('cyclotron')
.category('imthescatmanbebobebobeboeboboeoebobeoboebboeboeboeboeboeboeboeobeobeboebooeboeeoboeboeboebo')
.setMaxIOSize(1, 6, 1, 6)
.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
.setSound(GTSoundEntries.CENTRIFUGE)

event.create('manifold_collapsing')
        .category('ultimate')
        .setEUIO('in')
        .setMaxIOSize(1, 6, 1, 6)
        .setSound(GTSoundEntries.CENTRIFUGE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_EXTRACT, FillDirection.LEFT_TO_RIGHT)


})

GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('cyclotron', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes(['cyclotron', 'manifold_collapsing'])
    .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
    .appearanceBlock(() => Block.getBlock("gtceu:vibration_safe_casing"))
    .pattern(definition => FactoryBlockPattern.start()
    .aisle("BBBBB", "BCCCB", "BCCCB", "BCCCB", "BBCBB", "ABBBA", "AABAA")
    .aisle("BBBBB", "CADAC", "CAAAC", "CADAC", "BAAAB", "BADAB", "ABBBA")
    .aisle("BBBBB", "CAFAC", "CDFDC", "CAFAC", "CDFDC", "BAFAB", "BBFBB")
    .aisle("BBBBB", "CADAC", "CAAAC", "CADAC", "BAAAB", "BADAB", "ABBBA")
    .aisle("BBEBB", "BCCCB", "BCCCB", "BCCCB", "BBCBB", "ABBBA", "AABAA")
   .where("A", Predicates.any())
   .where("B", Predicates.blocks("gtceu:vibration_safe_casing")
        .or(Predicates.autoAbilities(definition.getRecipeTypes()))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
        .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1)))
   .where("C", Predicates.blocks("kubejs:obsidian_glass"))
   .where("D", Predicates.blocks("gtceu:titanium_pipe_casing"))
   .where("E", Predicates.controller(Predicates.blocks(definition.get())))
   .where("F", Predicates.blocks("gtceu:titanium_gearbox"))
.build())
.workableCasingModel('gtceu:block/casings/solid/vibration_safe_casing', 
    'gtceu:block/machines/centrifuge')

    event.create('mythrolyc_manifold_collapsing_engine', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes(['cyclotron', 'manifold_collapsing'])
    .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH])
    .appearanceBlock(() => Block.getBlock("gtceu:mythrovirdyne_casing"))
    .pattern(definition => FactoryBlockPattern.start()
    .aisle("aaabbbbbbbbbbbbbaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
    .aisle("aabbcccccbcccccbbaa", "aaaabcccdddcccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabcccdddcccbaaaa", "aaaabaaaaaaaaabaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
    .aisle("abbbcccccbcccccbbba", "aaaacccccccccccaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacccccccccccaaaa", "aaaabcccccccccbaaaa", "aaaabaaaaaaaaabaaaa", "aaaabaaaaaaaaabaaaa", "aaaaaaaaaaaaaaaaaaa")
    .aisle("bbbbcccccbcccccbbbb", "aaabccaaaeaaaccbaaa", "aaabaaaaaeaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabaaaaaaaaeaabaaa", "aaabaaaaaaaaeaabaaa", "aaabaaaaaaaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabccaaaaaaaccbaaa", "aaabbbbbbbbbbbbbaaa", "aaabbbbbbbbbbbbbaaa", "aaabbbbbbbbbbbbbaaa", "aaaaabababababaaaaa")
    .aisle("bccccccccbccccccccb", "abcccaaaaeaaaacccba", "abcaaaaaaeaaaaaacba", "abcaaaaaaaaaaaaacba", "abcaaaaaaaaaaaaacba", "abcaaaaaaaaaeaaacba", "abcaaaaaaaaaeaaacba", "abcaaaaaaaaaaaaacba", "abcaaaaaaaaaaaaacba", "abcaeaaaaaaaaaeacba", "abcaeaaaaaaaaaeacba", "abcccaaaaaaaaacccba", "abbbcbcbcbcbcbcbbba", "aabbaaaaaaaaaaabbaa", "aabbababababababbaa", "aaaabbbbbbbbbbbaaaa")
    .aisle("bccccccccbccccccccb", "acccaaaaaeaaaaaccca", "acaaaaaaaeaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaaaaaaeaaaaaca", "acaaaaaaaaaeaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaeaaaaaaaeaaaca", "acaaaeaaaaaaaeaaaca", "acccaaaaaaaaaaaccca", "aacbbcccccccccbbcaa", "aaabaaaaaaaaaaabaaa", "aaabbaaaaaaaaabbaaa", "aaabbbbbbbbbbbbbaaa")
    .aisle("bccccccccbccccccccb", "accaaaaaaeaaaaaacca", "acaaaaaaaeaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaeeaaaaaaeaaaaaca", "acaeeaaaaaaeaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaeaaaaaeaaaaca", "acaaaaeaaaaaeaaaaca", "accaaaaaaaaaaaaacca", "aacbcccbcbcbcccbcaa", "aaabaafffffffaabaaa", "aaabaaaaaaaaaaabaaa", "aaaabbbbbbbbbbbaaaa")
    .aisle("bccccccccbccccccccb", "accaaaaaaeaaaaaacca", "adcaaaaaaeaaaaaacda", "adcaaaaaaaaaaaaacda", "adcaaaaaaaaaaaaacda", "adcaaeeaaaeaaaaacda", "adcaaeeaaaeaaaaacda", "adcaaaaaaaaaaaaacda", "adcaaaaaaaaaaaaacda", "adcaaaaeaaaeaaaacda", "adcaaaaeaaaeaaaacda", "accaaaaaaaaaaaaacca", "aacbbcbbbbbbbcbbcaa", "aaabaafgggggfaabaaa", "aaabbaahhhhhaabbaaa", "aaabbbbiiiiibbbbaaa")
    .aisle("bccccccccbccccccccb", "adcaaaaajejaaaaacda", "adaaaaaajejaaaaaada", "adaaaaaaaaaaaaaaada", "adaaaaaaaaaaaaaaada", "adaaaaaeejeaaaaaada", "adaaaaaeejeaaaaaada", "adaaaaaaaaaaaaaaada", "adaaaaaaaaaaaaaaada", "adaaaaaaejeaaaaaada", "adaaaaaaejeaaaaaada", "adcaaaaaaaaaaaaacda", "aacbcccbaaabcccbcaa", "aaabaafgjjjgfaabaaa", "aaabaaahhhhhaaabaaa", "aaaabbbiiiiibbbaaaa")
    .aisle("bbbbbbbbbbbbbbbbbbb", "adceeeeeejeeeeeecda", "adaeeeeeejeeeeeeada", "adaaaaaaajaaaaaaada", "adaaaaaaajaaaaaaada", "adaaaaaajjjaaaaaada", "adaaaaaajjjaaaaaada", "adaaaaaaajaaaaaaada", "adaaaaaaajaaaaaaada", "adaaaaaajjjaaaaaada", "adaaaaaajjjaaaaaada", "adcaaaaaajaaaaaacda", "aacbbcbbagabbcbbcaa", "aaabaafgjjjgfaabaaa", "aaabbaahhhhhaabbaaa", "aaabbbbiiiiibbbbaaa")
    .aisle("bccccccccbccccccccb", "adcaaaaajejaaaaacda", "adaaaaaajejaaaaaada", "adaaaaaaaaaaaaaaada", "adaaaaaaaaaaaaaaada", "adaaaaaaejeeaaaaada", "adaaaaaaejeeaaaaada", "adaaaaaaaaaaaaaaada", "adaaaaaaaaaaaaaaada", "adaaaaaaejeaaaaaada", "adaaaaaaejeaaaaaada", "adcaaaaaaaaaaaaacda", "aacbcccbaaabcccbcaa", "aaabaafgjjjgfaabaaa", "aaabaaahhhhhaaabaaa", "aaaabbbiiiiibbbaaaa")
    .aisle("bccccccccbccccccccb", "accaaaaaaeaaaaaacca", "adcaaaaaaeaaaaaacda", "adcaaaaaaaaaaaaacda", "adcaaaaaaaaaaaaacda", "adcaaaaaeaaaeeaacda", "adcaaaaaeaaaeeaacda", "adcaaaaaaaaaaaaacda", "adcaaaaaaaaaaaaacda", "adcaaaaeaaaeaaaacda", "adcaaaaeaaaeaaaacda", "accaaaaaaaaaaaaacca", "aacbbcbbbbbbbcbbcaa", "aaabaafgggggfaabaaa", "aaabbaahhhhhaabbaaa", "aaabbbbiiiiibbbbaaa")
    .aisle("bccccccccbccccccccb", "accaaaaaaeaaaaaacca", "acaaaaaaaeaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaaeaaaaaaeeaca", "acaaaaaeaaaaaaeeaca", "acaaaaaaaaaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaeaaaaaeaaaaca", "acaaaaeaaaaaeaaaaca", "accaaaaaaaaaaaaacca", "aacbcccbcbcbcccbcaa", "aaabaafffffffaabaaa", "aaabaaaaaaaaaaabaaa", "aaaabbbbbbbbbbbaaaa")
    .aisle("bccccccccbccccccccb", "acccaaaaaeaaaaaccca", "acaaaaaaaeaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaaeaaaaaaaaaca", "acaaaaaeaaaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaaaaaaaaaaaaaca", "acaaaeaaaaaaaeaaaca", "acaaaeaaaaaaaeaaaca", "acccaaaaaaaaaaaccca", "aacbbcccccccccbbcaa", "aaabaaaaaaaaaaabaaa", "aaabbaaaaaaaaabbaaa", "aaabbbbbbbbbbbbbaaa")
    .aisle("bccccccccbccccccccb", "abcccaaaaeaaaacccba", "abcaaaaaaeaaaaaacba", "abcaaaaaaaaaaaaacba", "abcaaaaaaaaaaaaacba", "abcaaaeaaaaaaaaacba", "abcaaaeaaaaaaaaacba", "abcaaaaaaaaaaaaacba", "abcaaaaaaaaaaaaacba", "abcaeaaaaaaaaaeacba", "abcaeaaaaaaaaaeacba", "abcccaaaaaaaaacccba", "abbbcbcbcbcbcbcbbba", "aabbaaaaaaaaaaabbaa", "aabbababababababbaa", "aaaabbbbbbbbbbbaaaa")
    .aisle("bbbbcccccbcccccbbbb", "aaabccaaaeaaaccbaaa", "aaabaaaaaeaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabaaeaaaaaaaabaaa", "aaabaaeaaaaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabaaaaaaaaaaabaaa", "aaabccaaaaaaaccbaaa", "aaabbbbbbbbbbbbbaaa", "aaabbbbbbbbbbbbbaaa", "aaabbbbbbbbbbbbbaaa", "aaaaabababababaaaaa")
    .aisle("abbbcccccbcccccbbba", "aaaacccccccccccaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacaacaaacaacaaaa", "aaaacccccccccccaaaa", "aaaabcccccccccbaaaa", "aaaabaaaaaaaaabaaaa", "aaaabaaaaaaaaabaaaa", "aaaaaaaaaaaaaaaaaaa")
    .aisle("aabbcccccbcccccbbaa", "aaaabcccdddcccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabccdddddccbaaaa", "aaaabcccdddcccbaaaa", "aaaabaaaaaaaaabaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
    .aisle("aaabbbbbbkbbbbbbaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
    .where("a", Predicates.any())
    .where("b", Predicates.blocks("gtceu:mythrovirdyne_casing")
        .or(Predicates.autoAbilities(definition.getRecipeTypes()))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
        .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1)))
    .where("c", Predicates.blocks("gtceu:mythrolyc_umbraloy_casing"))
    .where("d", Predicates.blocks("kubejs:aetherite_glass"))
    .where("e", Predicates.blocks("gtceu:abyssal_netherite_pipe_casing"))
    .where("f", Predicates.blocks("gtceu:abyssal_netherite_heat_escape_casing"))
    .where("g", Predicates.blocks("gtceu:abyssal_netherite_gearbox_casing"))
    .where("h", Predicates.blocks("gtceu:abyssal_netherite_engine_intake"))
    .where("i", Predicates.blocks("gtceu:mythrovirdyne_frame"))
    .where("j", Predicates.blocks("gtceu:abyssal_netherite_machine_casing"))
    .where("k", Predicates.controller(Predicates.blocks(definition.get())))
.build())
.workableCasingModel('gtceu:block/casings/solid/mythrovirdyne_casing', 'gtceu:block/machines/centrifuge')
})