GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event
    .create('echoite_exile')
    .category('ifuckinghatepears™')
    .setEUIO('in')
    .setMaxIOSize(3, 1, 2, 1)
    .setSlotOverlay(false, false, GuiTextures.SLOT)
    .setProgressBar(GuiTextures.PROGRESS_BAR_MIXER, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.MIXER)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('effervescent_echoite_exile', "multiblock")
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT_SUBTICK])
        .recipeTypes([GTRecipeTypes.get('echoite_exile')])
        .appearanceBlock(() => Block.getBlock("gtceu:magikstone_casing"))
        .pattern(definition => FactoryBlockPattern.start()
        .aisle('      E      ', '      E      ', '             ', '             ', '             ', '             ', '             ', '             ', '             ')
        .aisle('     EPE     ', '     EPE     ', '      E      ', '             ', '             ', '             ', '             ', '             ', '             ')
        .aisle('      E      ', '      E      ', '     EPE     ', '      E      ', '             ', '             ', '             ', '             ', '             ')
        .aisle('             ', '      E      ', '     EPE     ', '      E      ', '             ', '             ', '             ', '             ', '             ')
        .aisle('             ', '     MMM     ', '     MPM     ', '     MMM     ', '     MMM     ', '     MMM     ', '      F      ', '      F      ', '             ')
        .aisle(' E         E ', ' E  MMMMM  E ', '  EEM P MEE  ', '    M   M    ', '    M P M    ', '    M   M    ', '             ', '      F      ', '      F      ')
        .aisle('EPE       EPE', 'EPEEMMMMMEEPE', ' EPPPPPPPPPE ', '  EEM P MEE  ', '    MPPPM    ', '    M G M    ', '    F G F    ', '    FFGFF    ', '     FFF     ')
        .aisle(' E         E ', ' E  MMMMM  E ', '  EEM P MEE  ', '    M   M    ', '    M P M    ', '    M   M    ', '             ', '      F      ', '      F      ')
        .aisle('             ', '     MMM     ', '     MXM     ', '     MMM     ', '     MMM     ', '     MMM     ', '      F      ', '      F      ', '             ')
        .where(' ', Predicates.any())
        .where('E', Predicates.blocks('gtceu:frostproof_machine_casing'))
        .where('F', Predicates.blocks('gtceu:nexus_steel_frame'))
        .where('G', Predicates.blocks('gtceu:steel_gearbox'))
        .where('M', Predicates.blocks('gtceu:magikstone_casing')
            .or(Predicates.autoAbilities(definition.getRecipeTypes()))
            .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1)))
        .where('P', Predicates.blocks('gtceu:steel_pipe_casing'))
        .where('X', Predicates.controller(Predicates.blocks(definition.get())))
        .build())
        .workableCasingModel('gtceu:block/casings/solid/magikstone_casing',
        'gtceu:block/machines/mixer')
})