GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('nuclear_dissolvant')
    .setMaxIOSize(1, 1, 2, 4)
    .category('nuclear')
    .setEUIO('in')
    .setSlotOverlay(true, true, GuiTextures.ATOMIC_OVERLAY_2)
    .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.ELECTROLYZER)

    event.create('extraction_column')
    .setMaxIOSize(0, 0, 2, 2)
    .category('nuclear')
    .setEUIO('in')
    .setSlotOverlay(true, true, GuiTextures.ATOMIC_OVERLAY_2)
    .setProgressBar(GuiTextures.PROGRESS_BAR_FUSION, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.CHEMICAL)

    event.create('scrubbing_column')
    .setMaxIOSize(0, 0, 2, 2)
    .category('nuclear')
    .setEUIO('in')
    .setSlotOverlay(true, true, GuiTextures.ATOMIC_OVERLAY_2)
    .setProgressBar(GuiTextures.PROGRESS_BAR_FUSION, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.SPRAY_CAN_TOOL)

    event.create('partition_column')
    .setMaxIOSize(0, 0, 2, 2)
    .category('nuclear')
    .setEUIO('in')
    .setSlotOverlay(true, true, GuiTextures.ATOMIC_OVERLAY_2)
    .setProgressBar(GuiTextures.PROGRESS_BAR_FUSION, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.SPRAY_CAN_TOOL)
    

    event.create('stripping_column')
    .setMaxIOSize(0, 0, 2, 2)
    .category('nuclear')
    .setEUIO('in')
    .setSlotOverlay(true, true, GuiTextures.ATOMIC_OVERLAY_2)
    .setProgressBar(GuiTextures.PROGRESS_BAR_FUSION, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.SPRAY_CAN_TOOL)

    event.create('nuclear_turbine')
    .category('nuclear')
    .setMaxIOSize(0, 0, 1, 1)
    .setSlotOverlay(true, true, GuiTextures.TURBINE_OVERLAY)
    .setProgressBar(GuiTextures.PROGRESS_BAR_GAS_COLLECTOR, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.JET_ENGINE)

    event.create('nuclear_fission')
    .category('nuclear')
    .setMaxIOSize(1, 1, 1, 1)
    .setEUIO('in')
    .setSlotOverlay(true, true, GuiTextures.TURBINE_OVERLAY)
    .setProgressBar(GuiTextures.PROGRESS_BAR_GAS_COLLECTOR, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.JET_ENGINE)

    event.create('supercritical_fission')
    .category('supernuclear')
    .setMaxIOSize(2,1,0,1)
    .setSlotOverlay(true, true, GuiTextures.VIAL_OVERLAY_1)
    .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.JET_ENGINE)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
// Nuclear Dissolvant
event.create("nuclear_dissolvant", "multiblock")
.rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes([GTRecipeTypes.get('nuclear_dissolvant')])
    .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT, (machine, recipe) => TemperatureMaximum(machine, recipe)])
    .appearanceBlock(() => Block.getBlock("gtceu:atomic_casing"))
    .pattern(definition => FactoryBlockPattern.start()
.aisle("BBBBBBB", "BBBBBBB", "CCCCCCC", "BBBBBBB", "AAAAAAA")
.aisle("BBBBBBB", "BDDDDDB", "CFFFFFC", "BDDDDDB", "ABBBBBA")
.aisle("BBBBBBB", "BDGGGDB", "CFCCCFC", "BDBBBDB", "ABAAABA")
.aisle("BBBXBBB", "BBGGGBB", "BEGGGEB", "BBBBBBB", "AAAAAAA")
   .where("A", Predicates.any())
   .where("B", Predicates.blocks("gtceu:atomic_casing")
        .or(Predicates.autoAbilities(definition.getRecipeTypes()))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
   .where("C", Predicates.blocks("gtceu:rtm_alloy_coil_block"))
   .where("D", Predicates.blocks("gtceu:electrolytic_cell"))
   .where("E", Predicates.blocks("gtceu:stable_machine_casing"))
   .where("F", Predicates.blocks("gtceu:titanium_pipe_casing"))
   .where("G", Predicates.blocks("kubejs:signalum_glass"))
   .where("X", Predicates.controller(Predicates.blocks(definition.get())))
.build())
.workableCasingModel('gtceu:block/casings/solid/atomic_casing',
        'gtceu:block/machines/extractor')


// Extraction Column
event.create("extraction_column", "multiblock")
.rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes([GTRecipeTypes.get('extraction_column')])
    .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
    .appearanceBlock(() => Block.getBlock("gtceu:atomic_casing"))
    .pattern(definition => FactoryBlockPattern.start()
.aisle("CAAAC", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "ACCAA")
.aisle("ADFDA", "CDFDA", "AEDFA", "AEDFC", "CDEDA", "ADEDA", "AFDEC", "CFDEA", "ADFDA", "ADFDC", "CEDFA", "AEDFA", "ADEDC", "CDEDA", "AFDEA", "AFDEC", "CDFDA", "ADFDC")
.aisle("AEAEA", "AEAEA", "CDADC", "ADADA", "AFAFA", "CFAFC", "ADADA", "ADADA", "CEAEC", "AEAEA", "ADADA", "CDADC", "AFAFA", "AFAFA", "CDADC", "ADADA", "AEAEA", "CEAEC")
.aisle("ADFDA", "ADFDC", "AFDEA", "CFDEA", "ADEDC", "ADEDA", "CEDFA", "AEDFC", "ADFDA", "CDFDA", "AFDEC", "AFDEA", "CDEDA", "ADEDC", "AEDFA", "CEDFA", "ADFDC", "CDFDA")
.aisle("CAAAC", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACCA")
.aisle("BBXBB", "BBABB", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA")
   .where("A", Predicates.any())
   .where("B", Predicates.blocks("gtceu:atomic_casing")
        .or(Predicates.autoAbilities(definition.getRecipeTypes()))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
   .where("C", Predicates.blocks("gtceu:titanium_pipe_casing"))
   .where("D", Predicates.blocks("gtceu:manasteel_frame"))
   .where("E", Predicates.blocks("gtceu:rtm_alloy_coil_block"))
   .where("F", Predicates.blocks("gtceu:magnetic_neodymium_block"))
   .where("X", Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel('gtceu:block/casings/solid/atomic_casing',
        'gtceu:block/machines/extractor')


        // Scrubbing Column
event.create("scrubbing_column", "multiblock")
.rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes([GTRecipeTypes.get('scrubbing_column')])
    .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
    .appearanceBlock(() => Block.getBlock("gtceu:atomic_casing"))
    .pattern(definition => FactoryBlockPattern.start()
.aisle("CAAAC", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "ACCAA")
.aisle("ADFDA", "CDFDA", "AEDFA", "AEDFC", "CDEDA", "ADEDA", "AFDEC", "CFDEA", "ADFDA", "ADFDC", "CEDFA", "AEDFA", "ADEDC", "CDEDA", "AFDEA", "AFDEC", "CDFDA", "ADFDC")
.aisle("AEAEA", "AEAEA", "CDADC", "ADADA", "AFAFA", "CFAFC", "ADADA", "ADADA", "CEAEC", "AEAEA", "ADADA", "CDADC", "AFAFA", "AFAFA", "CDADC", "ADADA", "AEAEA", "CEAEC")
.aisle("ADFDA", "ADFDC", "AFDEA", "CFDEA", "ADEDC", "ADEDA", "CEDFA", "AEDFC", "ADFDA", "CDFDA", "AFDEC", "AFDEA", "CDEDA", "ADEDC", "AEDFA", "CEDFA", "ADFDC", "CDFDA")
.aisle("CAAAC", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACCA")
.aisle("BBXBB", "BBABB", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA")
   .where("A", Predicates.any())
   .where("B", Predicates.blocks("gtceu:atomic_casing")
        .or(Predicates.autoAbilities(definition.getRecipeTypes()))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
   .where("C", Predicates.blocks("gtceu:titanium_pipe_casing"))
   .where("D", Predicates.blocks("gtceu:manasteel_frame"))
   .where("E", Predicates.blocks("gtceu:rtm_alloy_coil_block"))
   .where("F", Predicates.blocks("gtceu:watertight_casing"))
   .where("X", Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel('gtceu:block/casings/solid/atomic_casing',
        'gtceu:block/machines/ore_washer')

                // Partition Column
event.create("partition_column", "multiblock")
.rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes([GTRecipeTypes.get('partition_column')])
    .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
    .appearanceBlock(() => Block.getBlock("gtceu:atomic_casing"))
    .pattern(definition => FactoryBlockPattern.start()
.aisle("CAAAC", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "ACCAA")
.aisle("ADFDA", "CDFDA", "AEDFA", "AEDFC", "CDEDA", "ADEDA", "AFDEC", "CFDEA", "ADFDA", "ADFDC", "CEDFA", "AEDFA", "ADEDC", "CDEDA", "AFDEA", "AFDEC", "CDFDA", "ADFDC")
.aisle("AEAEA", "AEAEA", "CDADC", "ADADA", "AFAFA", "CFAFC", "ADADA", "ADADA", "CEAEC", "AEAEA", "ADADA", "CDADC", "AFAFA", "AFAFA", "CDADC", "ADADA", "AEAEA", "CEAEC")
.aisle("ADFDA", "ADFDC", "AFDEA", "CFDEA", "ADEDC", "ADEDA", "CEDFA", "AEDFC", "ADFDA", "CDFDA", "AFDEC", "AFDEA", "CDEDA", "ADEDC", "AEDFA", "CEDFA", "ADFDC", "CDFDA")
.aisle("CAAAC", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACCA")
.aisle("BBXBB", "BBABB", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA")
   .where("A", Predicates.any())
   .where("B", Predicates.blocks("gtceu:atomic_casing")
        .or(Predicates.autoAbilities(definition.getRecipeTypes()))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
   .where("C", Predicates.blocks("gtceu:titanium_pipe_casing"))
   .where("D", Predicates.blocks("gtceu:manasteel_frame"))
   .where("E", Predicates.blocks("gtceu:rtm_alloy_coil_block"))
   .where("F", Predicates.blocks("gtceu:nexus_steel_casing"))
   .where("X", Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel('gtceu:block/casings/solid/atomic_casing',
        'gtceu:block/machines/extractor')

        // Stripping Column
event.create("stripping_column", "multiblock")
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes([GTRecipeTypes.get('stripping_column')])
    .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
    .appearanceBlock(() => Block.getBlock("gtceu:atomic_casing"))
    .pattern(definition => FactoryBlockPattern.start()
    .aisle("CAAAC", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "AACAA", "ACAAA", "AAACA", "ACCAA")
    .aisle("ADFDA", "CDFDA", "AEDFA", "AEDFC", "CDEDA", "ADEDA", "AFDEC", "CFDEA", "ADFDA", "ADFDC", "CEDFA", "AEDFA", "ADEDC", "CDEDA", "AFDEA", "AFDEC", "CDFDA", "ADFDC")
    .aisle("AEAEA", "AEAEA", "CDADC", "ADADA", "AFAFA", "CFAFC", "ADADA", "ADADA", "CEAEC", "AEAEA", "ADADA", "CDADC", "AFAFA", "AFAFA", "CDADC", "ADADA", "AEAEA", "CEAEC")
    .aisle("ADFDA", "ADFDC", "AFDEA", "CFDEA", "ADEDC", "ADEDA", "CEDFA", "AEDFC", "ADFDA", "CDFDA", "AFDEC", "AFDEA", "CDEDA", "ADEDC", "AEDFA", "CEDFA", "ADFDC", "CDFDA")
    .aisle("CAAAC", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACAA", "AAACA", "ACAAA", "AACCA")
    .aisle("BBXBB", "BBABB", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA")
    .where("A", Predicates.any())
    .where("B", Predicates.blocks("gtceu:atomic_casing")
        .or(Predicates.autoAbilities(definition.getRecipeTypes()))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
    .where("C", Predicates.blocks("gtceu:titanium_pipe_casing"))
    .where("D", Predicates.blocks("gtceu:manasteel_frame"))
    .where("E", Predicates.blocks("gtceu:rtm_alloy_coil_block"))
    .where("F", Predicates.blocks("gtceu:electrolytic_cell"))
    .where("X", Predicates.controller(Predicates.blocks(definition.get())))
    .build())
    .workableCasingModel('gtceu:block/casings/solid/atomic_casing',
        'gtceu:block/machines/extractor')

const $LargeTurbineMachine = Java.loadClass("com.gregtechceu.gtceu.common.machine.multiblock.generator.LargeTurbineMachine")
event.create('nuclear_turbine', 'multiblock')
    .machine((holder) => new $LargeTurbineMachine(holder, GTValues.EV))
    .rotationState(RotationState.ALL)
    .recipeTypes([GTRecipeTypes.get('nuclear_turbine')])
    .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE, (machine, recipe) => $LargeTurbineMachine.recipeModifier(machine, recipe)])
    .appearanceBlock(() => Block.getBlock("gtceu:titanium_turbine_casing"))
    .pattern(definition => FactoryBlockPattern.start()
    .aisle("BBBBBBB", "BCCCCCB", "BCCCCCB", "BCCCCCB", "BBBBBBB")
    .aisle("BDDDDDB", "BEEEEEB", "BFFFFFB", "BEEEEEB", "BDDDDDB")
    .aisle("BDDDDDB", "BFFFFFB", "GHHHHHI", "BFFFFFB", "BDDDDDB")
    .aisle("BDDDDDB", "BEEEEEB", "BFFFFFB", "BEEEEEB", "BDDDDDB")
    .aisle("BBBTBBB", "BCCCCCB", "BCCCCCB", "BCCCCCB", "BBBBBBB")
    .where("B", Predicates.blocks("gtceu:titanium_turbine_casing")
        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
    .where("C", Predicates.blocks("gtceu:laminated_glass"))
    .where("D", Predicates.blocks("gtceu:nonconducting_casing"))
    .where("E", Predicates.blocks("gtceu:titanium_gearbox"))
    .where("F", Predicates.blocks("gtceu:electrolytic_cell"))
    .where("G", Predicates.ability(PartAbility.ROTOR_HOLDER).setExactLimit(1))
    .where("H", Predicates.blocks("gtceu:titanium_pipe_casing"))
    .where("I", Predicates.abilities(PartAbility.OUTPUT_ENERGY).setMaxGlobalLimited(1).setPreviewCount(1))
    .where("T", Predicates.controller(Predicates.blocks(definition.get())))
    .build())
    .workableCasingModel('gtceu:block/casings/mechanic/machine_casing_turbine_titanium', 'gtceu:block/multiblock/generator/large_steam_turbine')

    event.create('nuclear_fission_reactor', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes([GTRecipeTypes.get('nuclear_fission')])
    .appearanceBlock(() => Block.getBlock("gtceu:atomic_casing"))
    .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH])
    .pattern(definition => FactoryBlockPattern.start()
    .aisle("ABBBBBA", "ABBBBBA", "ABBBBBA", "ABBBBBA", "ABBBBBA", "ABBBBBA", "ABBBBBA", "ABBBBBA", "ABBBBBA")
    .aisle("BBBBBBB", "BCCCCCB", "BCAAACB", "BCAAACB", "BCAAACB", "BCAAACB", "BCDDDCB", "BCCCCCB", "BBBBBBB")
    .aisle("BBBBBBB", "BCFCFCB", "BAFAFAB", "BAFAFAB", "BAFAFAB", "BAFAFAB", "BDFDFDB", "BCFCFCB", "BBBBBBB")
    .aisle("BBBBBBB", "BCCCCCB", "BAAAAAB", "BAAAAAB", "BAAAAAB", "BAAAAAB", "BDDDDDB", "BCCCCCB", "BBBBBBB")
    .aisle("BBBBBBB", "BCFCFCB", "BAFAFAB", "BAFAFAB", "BAFAFAB", "BAFAFAB", "BDFDFDB", "BCFCFCB", "BBBBBBB")
    .aisle("BBBCBBB", "BCCCCCB", "BCAAACB", "BCAAACB", "BCAAACB", "BCAAACB", "BCDDDCB", "BCCCCCB", "BBBCBBB")
    .aisle("BBBGBBB", "BBEHEBB", "BBEEEBB", "ABEEEBA", "ABEEEBA", "ABEEEBA", "ABEEEBA", "ABEEEBA", "ABBGBBA")
   .where("A", Predicates.any())
   .where("B", Predicates.blocks("gtceu:atomic_casing")
          .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1).setPreviewCount(1))
          .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
          .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
          .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1)))
     .where("C", Predicates.blocks("gtceu:titanium_pipe_casing"))
     .where("D", Predicates.blocks("minecraft:water"))
     .where("E", Predicates.blocks("kubejs:enderium_glass"))
     .where("F", Predicates.blocks("gtceu:fuel_assembly"))
     .where("G", Predicates.blocks("gtceu:stable_machine_casing")
          .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
          .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1)))
   .where("H", Predicates.controller(Predicates.blocks(definition.get())))
   .build())
   .workableCasingModel('gtceu:block/casings/solid/atomic_casing', 'gtceu:block/machines/nuclear_fission_reactor')

    event.create('heart_of_harmonia', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes([GTRecipeTypes.get('supercritical_fission')])
    .appearanceBlock(() => Block.getBlock("gtceu:robust_machine_casing"))
    .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
    .pattern(definition => FactoryBlockPattern.start()
.aisle("aaaaaaaaaaaacccccccaaaaaaaaaaaaa", "aaaaaaaaaaaabbbbbbbaaaaaaaaaaaaa", "aaaaaaaaaaaabbbbbbbaaaaaaaaaaaaa", "aaaaaaaaaaaabbbbbbbaaaaaaaaaaaaa", "aaaaaaaaaaaabbbbbbbaaaaaaaaaaaaa", "aaaaaaaaaaaabbbbbbbaaaaaaaaaaaaa", "aaaaaaaaaaaabbbbbbbaaaaaaaaaaaaa", "aaaaaaaaaaaabbbbbbbaaaaaaaaaaaaa", "aaaaaaaaaaaabbbbbbbaaaaaaaaaaaaa", "aaaaaaaaaaaacccccccaaaaaaaaaaaaa")
.aisle("aaaaaaaaaaacccccccccaaaaaaaaaaaa", "aaaaaaaaaaabbjkjkjbbaaaaaaaaaaaa", "aaaaaaaaaaabbjkjkjbbaaaaaaaaaaaa", "aaaaaaaaaaabbjkjkjbbaaaaaaaaaaaa", "aaaaaaaaaaabbjkjkjbbaaaaaaaaaaaa", "aaaaaaaaaaabbjkjkjbbaaaaaaaaaaaa", "aaaaaaaaaaabbjkjkjbbaaaaaaaaaaaa", "aaaaaaaaaaabbjkjkjbbaaaaaaaaaaaa", "aaaaaaaaaaabbjkjkjbbaaaaaaaaaaaa", "aaaaaaaaaaacccccccccaaaaaaaaaaaa")
.aisle("aaaaaaaaaacccccccccccaaaaaaaaaaa", "aaaaaaaaaabblkjkjkjbbaaaaaaaaaaa", "aaaaaaaaaabblkjkjkjbbaaaaaaaaaaa", "aaaaaaaaaabblkjkjkjbbaaaaaaaaaaa", "aaaaaaaaaabblkjkjkjbbaaaaaaaaaaa", "aaaaaaaaaabblkjkjkjbbaaaaaaaaaaa", "aaaaaaaaaabblkjkjkjbbaaaaaaaaaaa", "aaaaaaaaaabblkjkjkjbbaaaaaaaaaaa", "aaaaaaaaaabblkjkjkjbbaaaaaaaaaaa", "aaaaaaaaaacccccccccccaaaaaaaaaaa")
.aisle("bbbbbaaaaacccccccccccaaaaaabbbbb", "cfffbccaaabjklklklkjbaaaaccbfffc", "bfffbaaacccjklklklkjbcccaaabfffb", "bfffbacccabjklklklkjbaacccabfffb", "cfffbccaaabjklklklkjbaaaaccbfffc", "bbbbbaaaaabjklklklkjbaaaaaabbbbb", "aaaaaaaaaabjklklklkjbaaaaaaaaaaa", "aaaaaaaaaabjklklklkjbaaaaaaaaaaa", "aaaaaaaaaabjklklklkjbaaaaaaaaaaa", "aaaaaaaaaacccccccccccaaaaaaaaaaa")
.aisle("cbbbbccaaacccccccccccaaaaccbbbbc", "dggggggcccckjklklkjkcccccggggggo", "eiiiacccgggkjklklkjkggggcccaiiip", "ehhhacgggcckjklklkjkcccgggcahhhp", "dggggggcccckjklklkjkcccccggggggg", "cbbbbccaaabkjklklkjkbaaaaccbbbbc", "aaaaaaaaaabkjklklkjkbaaaaaaaaaaa", "aaaaaaaaaabkjklklkjkbaaaaaaaaaaa", "aaaaaaaaaabkjklklkjkbaaaaaaaaaaa", "aaaaaaaaaacccccccccccaaaaaaaaaaa")
.aisle("bbbbbacccacccccccccccaacccabbbbb", "ecccacgggcclmjjjkjmlcccgggcaccco", "ehhhccaaaaclmjjjkjmlcaaaaacchhhp", "ecccccaaaaclmjjjkjmlcaaaaacccccp", "ehhhacccggglmjjjkjmlggggcccahhhp", "bbbbbaaaccclmjjjkjmlbcccaaabbbbb", "aaaaaaaaaablmjjjkjmlbaaaaaaaaaaa", "aaaaaaaaaablmjjjkjmlbaaaaaaaaaaa", "aaaaaaaaaablmjjjkjmlbaaaaaaaaaaa", "aaaaaaaaaacccccccccccaaaaaaaaaaa")
.aisle("bbbbbaaaccccccccccccccccaaabbbbb", "ehhhacccggglmjkjjjmlggggcccahhho", "ecccccaaaaclmjkjjjmlcaaaaacccccp", "ehhhccaaaaclmjkjjjmlcaaaaacchhhp", "ecccacgggcclmjkjjjmlcccgggcacccp", "bbbbbacccablmjkjjjmlbaacccabbbbb", "aaaaaaaaaablmjkjjjmlbaaaaaaaaaaa", "aaaaaaaaaablmjkjjjmlbaaaaaaaaaaa", "aaaaaaaaaablmjkjjjmlbaaaaaaaaaaa", "aaaaaaaaaacccccccccccaaaaaaaaaaa")
.aisle("cbbbbccaaacccccccccccaaaaccbbbbc", "dggggggcccckjklklkjkcccccggggggo", "ehhhacgggcckjklklkjkcccgggcahhhp", "eiiiacccgggkjklklkjkggggcccaiiip", "dggggggcccckjklklkjkcccccggggggg", "cbbbbccaaabkjklklkjkbaaaaccbbbbc", "aaaaaaaaaabkjklklkjkbaaaaaaaaaaa", "aaaaaaaaaabkjklklkjkbaaaaaaaaaaa", "aaaaaaaaaabkjklklkjkbaaaaaaaaaaa", "aaaaaaaaaacccccccccccaaaaaaaaaaa")
.aisle("bbbbbaaaaacccccccccccaaaaaabbbbb", "cfffbccaaabmkjklklkmbaaaaccbfffc", "bfffbacccabmkjklklkmbaacccabfffb", "bfffbaaaccbmkjklklkmbcccaaabfffb", "cfffbccaaabmkjklklkmbaaaaccbfffc", "bbbbbaaaaabmkjklklkmbaaaaaabbbbb", "aaaaaaaaaabmkjklklkmbaaaaaaaaaaa", "aaaaaaaaaabmkjklklkmbaaaaaaaaaaa", "aaaaaaaaaabmkjklklkmbaaaaaaaaaaa", "aaaaaaaaaacccccccccccaaaaaaaaaaa")
.aisle("aaaaaaaaaacccccccccccaaaaaaaaaaa", "aaaaaaaaaabbmkjkjkmbbaaaaaaaaaaa", "aaaaaaaaaabfmkjkjkmfbaaaaaaaaaaa", "aaaaaaaaaabfmkjkjkmfbaaaaaaaaaaa", "aaaaaaaaaabfmkjkjkmfbaaaaaaaaaaa", "aaaaaaaaaabfmkjkjkmfbaaaaaaaaaaa", "aaaaaaaaaabfmkjkjkmfbaaaaaaaaaaa", "aaaaaaaaaabfmkjkjkmfbaaaaaaaaaaa", "aaaaaaaaaabbmkjkjkmbbaaaaaaaaaaa", "aaaaaaaaaacccccccccccaaaaaaaaaaa")
.aisle("aaaaaaaaaaacccccccccaaaaaaaaaaaa", "aaaaaaaaaaabbmmmmmbbaaaaaaaaaaaa", "aaaaaaaaaaaffmmmmmffaaaaaaaaaaaa", "aaaaaaaaaaaffmmmmmffaaaaaaaaaaaa", "aaaaaaaaaaaffmmmmmffaaaaaaaaaaaa", "aaaaaaaaaaaffmmmmmffaaaaaaaaaaaa", "aaaaaaaaaaaffmmmmmffaaaaaaaaaaaa", "aaaaaaaaaaaffmmmmmffaaaaaaaaaaaa", "aaaaaaaaaaabbmmmmmbbaaaaaaaaaaaa", "aaaaaaaaaaacccccccccaaaaaaaaaaaa")
.aisle("aaaaaaaaaaaacccccccaaaaaaaaaaaaa", "aaaaaaaaaaaabbbnbbbaaaaaaaaaaaaa", "aaaaaaaaaaaafffffffaaaaaaaaaaaaa", "aaaaaaaaaaaafffffffaaaaaaaaaaaaa", "aaaaaaaaaaaafffffffaaaaaaaaaaaaa", "aaaaaaaaaaaafffffffaaaaaaaaaaaaa", "aaaaaaaaaaaafffffffaaaaaaaaaaaaa", "aaaaaaaaaaaafffffffaaaaaaaaaaaaa", "aaaaaaaaaaaabbbbbbbaaaaaaaaaaaaa", "aaaaaaaaaaaacccccccaaaaaaaaaaaaa")
    .where("a", Predicates.any())
    .where("b", Predicates.blocks("gtceu:atomic_casing"))
    .where("c", Predicates.blocks("gtceu:robust_machine_casing"))
    .where("d", Predicates.blocks("gtceu:robust_machine_casing")
        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(4)))
    .where("e", Predicates.blocks("gtceu:robust_machine_casing")
        .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1)))
    .where("f", Predicates.blocks("gtceu:fusion_glass"))
    .where("g", Predicates.blocks("gtceu:tungstensteel_pipe_casing"))
    .where("h", Predicates.blocks("gtceu:tungstensteel_gearbox"))
    .where("i", Predicates.blocks("gtceu:electrolytic_cell"))
    .where("j", Predicates.blocks("gtceu:beryllium_block"))
    .where("k", Predicates.blocks("gtceu:fuel_assembly"))
    .where("l", Predicates.blocks("gtceu:graphene_block"))
    .where("m", Predicates.blocks("minecraft:water"))
    .where("n", Predicates.controller(Predicates.blocks(definition.get())))
    .where("o", Predicates.blocks("gtceu:robust_machine_casing")
        .or(Predicates.abilities(PartAbility.OUTPUT_LASER).setMaxGlobalLimited(2))
        .or(Predicates.abilities(PartAbility.OUTPUT_ENERGY).setMaxGlobalLimited(2))
        .or(Predicates.abilities(PartAbility.SUBSTATION_OUTPUT_ENERGY).setMaxGlobalLimited(2)))
    .where("p", Predicates.blocks("gtceu:robust_machine_casing")
        .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1)))
    .build())
    .workableCasingModel('gtceu:block/casings/solid/machine_casing_robust_tungstensteel', 'gtceu:block/machines/nuclear_fission_reactor')



})