GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
event.create('electric_ore_processing_plant')
    .category('technological')
    .setMaxIOSize(1, 8, 2, 1)
    .setSound(GTSoundEntries.BATH)
    .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('plant_ore_processing')
        .category('technological')
        .setEUIO('in')
        .setMaxIOSize(1, 6, 1, 0)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW , FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.FURNACE)
})
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('ore_processing_factory', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes('electric_ore_processing_plant')
    .recipeModifier(GTRecipeModifiers.OC_PERFECT)
    .appearanceBlock(() => Block.getBlock("gtceu:nexus_steel_casing"))
    .pattern(definition => FactoryBlockPattern.start()
    .aisle(' AAA ', ' FFF ', ' FFF ', '  F  ', '     ', '     ', '     ')
    .aisle('AFFFA', 'FG GF', 'F   F', ' F F ', ' FFF ', '  F  ', '  B  ')
    .aisle('AFFFA', 'F P F', 'F P F', 'F P F', ' FPF ', ' FPF ', ' B B ')
    .aisle('AFFFA', 'FG GF', 'F   F', ' F F ', ' FFF ', '  F  ', '  B  ')
    .aisle(' AAA ', ' FCF ', ' FFF ', '  F  ', '     ', '     ', '     ')
    .where('C', Predicates.controller(Predicates.blocks(definition.get())))
    .where('F', Predicates.blocks('gtceu:nexus_steel_casing')
        .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1)))
    .where('P', Predicates.blocks(GTBlocks.CASING_STEEL_PIPE.get()))
    .where('G', Predicates.blocks('gtceu:steel_gearbox'))
    .where('A', Predicates.blocks('gtceu:steel_firebox_casing'))
    .where('B', Predicates.blocks('gtceu:igneous_bronze_casing'))
    .where(' ', Predicates.any())
    .build())
    .workableCasingModel("gtceu:block/casings/solid/nexus_steel_casing", "kubejs:block/multiblock/primitive_blast_furnace")

     event.create('ore_processing_plant', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeType('plant_ore_processing')
    .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
    .appearanceBlock(GTBlocks.CASING_TUNGSTENSTEEL_ROBUST)
    .pattern(definition => FactoryBlockPattern.start()
    .aisle(' AAA ', ' FFF ', ' FFF ', '  F  ', '     ', '     ', '     ')
    .aisle('AFFFA', 'FG GF', 'F   F', ' F F ', ' FFF ', '  F  ', '  B  ')
    .aisle('AFFFA', 'F P F', 'F P F', 'F P F', ' FPF ', ' FMF ', ' B B ')
    .aisle('AFFFA', 'FG GF', 'F   F', ' F F ', ' FFF ', '  F  ', '  B  ')
    .aisle(' AAA ', ' FCF ', ' FFF ', '  F  ', '     ', '     ', '     ')
    .where('C', Predicates.controller(Predicates.blocks(definition.get())))
    .where('F', Predicates.blocks(GTBlocks.CASING_TUNGSTENSTEEL_ROBUST.get()) //All Hatches have a max
        .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
        .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1)))
    .where('M', Predicates.abilities(PartAbility.MUFFLER))
    .where('P', Predicates.blocks(GTBlocks.CASING_TUNGSTENSTEEL_PIPE.get()))
    .where('G', Predicates.blocks(GTBlocks.CASING_TUNGSTENSTEEL_GEARBOX.get()))
    .where('A', Predicates.blocks(GTBlocks.FIREBOX_TUNGSTENSTEEL.get()))
    .where('B', Predicates.blocks('gtceu:stable_machine_casing'))
    .where(' ', Predicates.any())
    .build())
    .workableCasingModel('gtceu:block/casings/solid/machine_casing_robust_tungstensteel', 'kubejs:block/multiblock/primitive_blast_furnace')
})