GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
event.create('electric_ore_processing_plant')
    .category('technological')
    .setMaxIOSize(1, 8, 2, 1)
    .setSound(GTSoundEntries.BATH)
    .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('plant_ore_processing')
        .category('technological')
        .setMaxIOSize(1, 6, 1, 0)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW , FillDirection.LEFT_TO_RIGHT)
		.setSound(GTSoundEntries.FURNACE)

    event.create('array_ore_processing')
        .category('technological')
        .setMaxIOSize(1, 8, 2, 0)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.FURNACE)
})
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('ore_processing_factory', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes('electric_ore_processing_plant')
    .recipeModifier(GTRecipeModifiers.OC_NON_PERFECT)
    .appearanceBlock(() => Block.getBlock("gtceu:nexus_steel_casing"))
    .pattern(definition => FactoryBlockPattern.start()
    .aisle(' AAA ', ' FFF ', ' FFF ', '  F  ', '     ', '     ', '     ')
    .aisle('AFFFA', 'FG GF', 'F   F', ' F F ', ' FFF ', '  F  ', '  B  ')
    .aisle('AFFFA', 'F P F', 'F P F', 'F P F', ' FPF ', ' FPF ', ' B B ')
    .aisle('AFFFA', 'FG GF', 'F   F', ' F F ', ' FFF ', '  F  ', '  B  ')
    .aisle(' AAA ', ' FCF ', ' FFF ', '  F  ', '     ', '     ', '     ')
    .where('C', Predicates.controller(Predicates.blocks(definition.get())))
    .where('F', Predicates.blocks('gtceu:nexus_steel_casing')
        .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1)))
    .where('P', Predicates.blocks(GTBlocks.CASING_STEEL_PIPE.get()))
    .where('G', Predicates.blocks('gtceu:steel_gearbox'))
    .where('A', Predicates.blocks('gtceu:steel_firebox_casing'))
    .where('B', Predicates.blocks('gtceu:igneous_bronze_casing'))
    .where(' ', Predicates.any())
    .build())
    .workableCasingModel("gtceu:block/casings/solid/nexus_steel_casing", "kubejs:block/multiblock/primitive_blast_furnace")

    event.create('ore_processing_plant', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes('plant_ore_processing')
    .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
    .appearanceBlock(GTBlocks.CASING_TUNGSTENSTEEL_ROBUST)
    .pattern(definition => FactoryBlockPattern.start()
    .aisle(' AAA ', ' FFF ', ' FFF ', '  F  ', '     ', '     ', '     ')
    .aisle('AFFFA', 'FG GF', 'F   F', ' F F ', ' FFF ', '  F  ', '  B  ')
    .aisle('AFFFA', 'F P F', 'F P F', 'F P F', ' FPF ', ' FMF ', ' B B ')
    .aisle('AFFFA', 'FG GF', 'F   F', ' F F ', ' FFF ', '  F  ', '  B  ')
    .aisle(' AAA ', ' FCF ', ' FFF ', '  F  ', '     ', '     ', '     ')
    .where('C', Predicates.controller(Predicates.blocks(definition.get())))
    .where('F', Predicates.blocks(GTBlocks.CASING_TUNGSTENSTEEL_ROBUST.get()) //All Hatches have a max
        .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
        .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1)))
    .where('M', Predicates.abilities(PartAbility.MUFFLER))
    .where('P', Predicates.blocks(GTBlocks.CASING_TUNGSTENSTEEL_PIPE.get()))
    .where('G', Predicates.blocks(GTBlocks.CASING_TUNGSTENSTEEL_GEARBOX.get()))
    .where('A', Predicates.blocks(GTBlocks.FIREBOX_TUNGSTENSTEEL.get()))
    .where('B', Predicates.blocks('gtceu:stable_machine_casing'))
    .where(' ', Predicates.any())
    .build())
    .workableCasingModel('gtceu:block/casings/solid/machine_casing_robust_tungstensteel', 'kubejs:block/multiblock/primitive_blast_furnace')

    event.create('ore_processing_array', 'multiblock')
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes('array_ore_processing')
    .recipeModifiers([GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH])
    .appearanceBlock(() => Block.getBlock("gtceu:vhaelcryite_casing"))
    .pattern(definition => FactoryBlockPattern.start()
    .aisle("aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaabaaaaabaaaaabaaa", "cccbaaaaabaaaaabccc", "aaabbbbbbbbbbbbbaaa", "cccbaaaaabaaaaabccc", "aaabaaaaabaaaaabaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
    .aisle("aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaabaaaaabaaaaabaaa", "abbbaaaaabaaaaabbba", "cbbbeeeeeeeeeeebbbc", "abbbeeeeebeeeeebbba", "cbbbeeeeeaeeeeebbbc", "abbbaaaaabaaaaabbba", "aaabaaaaabaaaaabaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
    .aisle("aaaaaaaaaaaaaaaaaaa", "aaabaaaaabaaaaabaaa", "abbbeeeeebeeeeebbba", "cbbbeeeeeeeeeeebbbc", "ccccaaaacccaaaacccc", "abbbbbbbbbbbbbbbbba", "ccccaaaacccaaaacccc", "cbbbeeeeeaeeeeebbbc", "abbbeeeeebeeeeebbba", "aaabaaaaabaaaaabaaa", "aaaaaaaaaaaaaaaaaaa")
    .aisle("aaabaaaaabaaaaabaaa", "abbbaaaaabaaaaabbba", "cbbbeeeeeeeeeeebbbc", "ccccaaccaaaccaacccc", "abbbaaaaaaaaaaabbba", "abbbaaaaaaaaaaaabba", "abbbaaaaaaaaaaabbba", "ccccaaccaaaccaacccc", "cbbbeeeeeaeeeeebbbc", "abbbaaaaabaaaaabbba", "aaabaaaaabaaaaabaaa")
    .aisle("cccbaaaaabaaaaabccc", "cbbbeeeeeeeeeeebbbc", "ccccccaaaaaaacccccc", "abbbaaaaaaaaaaabbba", "abbbaaaaaaaaaaaabba", "axaaaaaaaaaaaaaaaya", "abbbaaaaaaaaaaaabba", "abbbaaaaaaaaaaabbba", "ccccccaaaaaaacccccc", "cbbbeeeeeaeeeeebbbc", "cccbaaaaabaaaaabccc")
    .aisle("aaabbbbbbbbbbbbbaaa", "abbbeeeeebeeeeebbba", "abbbbbbbbbbbbbbbbba", "abbbgggggggggggabba", "axaaaaaaagaaaaaaaya", "axaaaaaaagaaaaaaaya", "axaaaaaaagaaaaaaaya", "abbbgggggggggggabba", "abbbbbbbbbbbbbbbbba", "abbbeeeeebeeeeebbba", "aaabbbbbbbbbbbbbaaa")
    .aisle("cccbaaaaabaaaaabccc", "cbbbeeeeeeeeeeebbbc", "ccccccaaaaaaacccccc", "abbbaaaaaaaaaaabbba", "abbbaaaaaaaaaaaabba", "axaaaaaaaaaaaaaaaya", "abbbaaaaaaaaaaaabba", "abbbaaaaaaaaaaabbba", "ccccccaaaaaaacccccc", "cbbbeeeeeaeeeeebbbc", "cccbaaaaabaaaaabccc")
    .aisle("aaabaaaaabaaaaabaaa", "abbbaaaaabaaaaabbba", "cbbbeeeeeeeeeeebbbc", "ccccaaccaaaccaacccc", "abbbaaaaaaaaaaabbba", "abbbaaaaaaaaaaaabba", "abbbaaaaaaaaaaabbba", "ccccaaccaaaccaacccc", "cbbbeeeeeaeeeeebbbc", "abbbaaaaabaaaaabbba", "aaabaaaaabaaaaabaaa")
    .aisle("aaaaaaaaaaaaaaaaaaa", "aaabaaaaabaaaaabaaa", "abbbeeeeebeeeeebbba", "cbbbeeeeeeeeeeebbbc", "ccccaaaacccaaaacccc", "abbbbbbbbbbbbbbbbba", "ccccaaaacccaaaacccc", "cbbbeeeeeaeeeeebbbc", "abbbeeeeebeeeeebbba", "aaabaaaaabaaaaabaaa", "aaaaaaaaaaaaaaaaaaa")
    .aisle("aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaabaaaaabaaaaabaaa", "abbbaaaaabaaaaabbba", "cbbbeeeeeeeeeeebbbc", "abbbeeeeebeeeeebbba", "cbbbeeeeeaeeeeebbbc", "abbbaaaaabaaaaabbba", "aaabaaaaabaaaaabaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
    .aisle("aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaabaaaaabaaaaabaaa", "cccbaaaabbbaaaabccc", "aaabbbbbbdbbbbbbaaa", "cccbaaaabbbaaaabccc", "aaabaaaaabaaaaabaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
    .where("a", Predicates.any())
    .where("b", Predicates.blocks("gtceu:vhaelcryite_casing"))
    .where("c", Predicates.blocks("gtceu:peek_pipe_casing"))
    .where("d", Predicates.controller(Predicates.blocks(definition.get())))
    .where("e", Predicates.blocks("gtceu:sulvan_steel_casing")
        .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(4).setPreviewCount(1)))
    .where("f", Predicates.blocks("gtceu:sulvan_steel_firebox_casing"))
    .where("g", Predicates.blocks("gtceu:sulvan_steel_gearbox_casing"))
    .where("x", Predicates.blocks("gtceu:sulvan_steel_firebox_casing")
        .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1)))
    .where("y", Predicates.blocks("gtceu:sulvan_steel_firebox_casing")
        .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1)))
        .build())
        .workableCasingModel('gtceu:block/casings/solid/vhaelcryite_casing', 'gtceu:block/multiblock/power_substation')

})