GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('alloying_kiln')
    .category('thefitnessgrampacertestisamultistageaerobiccapacitytestthatprogressivelygetsmoredifficult')
    .setEUIO('in')
    .setMaxIOSize(4, 2, 0, 0)
    .setSlotOverlay(false, false, GuiTextures.SLOT)
    .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.COMPRESSOR)

})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('primitive_alloyment_kiln', 'multiblock')
    .machine((holder) => new $SteamMulti(holder, 8))
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes([GTRecipeTypes.get('alloying_kiln'), GTRecipeTypes.get('alloy_smelter')])
    .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
    .pattern(definition => FactoryBlockPattern.start()
    .aisle('ATTSTTA', 'AISSSIA', 'AISSSIA', 'AISSSIA', 'ATTTTTA')
    .aisle('STSSSTS', 'SPAAAPS', 'SPPAPPS', 'SSPPPSS', 'ATSSSTA')
    .aisle('SSSSSSS', 'SAACAAS', 'SAACAAS', 'SSACASS', 'ATSSSTA')
    .aisle('STSSSTS', 'SPAAAPS', 'SPPAPPS', 'SSPPPSS', 'ATSSSTA')
    .aisle('ATTSTTA', 'AISSSIA', 'AISXSIA', 'AISSSIA', 'ATTTTTA')
    .where('A', Predicates.any())
    .where('C', Predicates.blocks('gtceu:cupronickel_coil_block'))
    .where('P', Predicates.blocks('gtceu:steel_frame'))
    .where('I', Predicates.blocks('gtceu:bronze_frame'))
    .where('S', Predicates.blocks('gtceu:firebricks')
            .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1)))
    .where('T', Predicates.blocks('gtceu:treated_wood_frame'))
    .where('X', Predicates.controller(Predicates.blocks(definition.get())))
    .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_primitive_bricks", "gtceu:block/machines/alloy_smelter")
})