GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('alloying_kiln')
    .category('technological')
    .setMaxIOSize(4, 2, 0, 0)
    .setSlotOverlay(false, false, GuiTextures.SLOT)
    .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('ore_processing_plant')
    .category('technological')
    .setMaxIOSize(1, 8, 2, 1)
    .setSound(GTSoundEntries.COMBUSTION)
    .setProgressBar(GuiTextures.PRIMITIVE_BLAST_FURNACE_PROGRESS_BAR, FillDirection.LEFT_TO_RIGHT)

    event.create('primitive_cylindrical_hearth')
    .category('primitive')
    .setMaxIOSize(5, 1, 0, 1)
    .setSound(GTSoundEntries.FURNACE)
    .setSlotOverlay(false, false, GuiTextures.SLOT)
    .setProgressBar(GuiTextures.PROGRESS_BAR_COKE_OVEN, FillDirection.LEFT_TO_RIGHT)

    event.create('primitive_coking_array')
    .category('primitive')
    .setMaxIOSize(4, 4, 1, 1)
    .setSound(GTSoundEntries.FURNACE)
    .setSlotOverlay(false, false, GuiTextures.SLOT)
    .setProgressBar(GuiTextures.PROGRESS_BAR_COKE_OVEN, FillDirection.LEFT_TO_RIGHT)

})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('primitive_alloyment_kiln', 'multiblock')
    .machine((holder) => new $SteamMulti(holder, 8))
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes([GTRecipeTypes.get('alloying_kiln'), GTRecipeTypes.get('alloy_smelter')])
    .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
    .pattern(definition => FactoryBlockPattern.start()
    .aisle('ATTSTTA', 'AISSSIA', 'AISSSIA', 'AISSSIA', 'ATTTTTA')
    .aisle('STSSSTS', 'SPAAAPS', 'SPPAPPS', 'SSPPPSS', 'ATSSSTA')
    .aisle('SSSSSSS', 'SAACAAS', 'SAACAAS', 'SSACASS', 'ATSSSTA')
    .aisle('STSSSTS', 'SPAAAPS', 'SPPAPPS', 'SSPPPSS', 'ATSSSTA')
    .aisle('ATTSTTA', 'AISSSIA', 'AISXSIA', 'AISSSIA', 'ATTTTTA')
    .where('A', Predicates.any())
    .where('C', Predicates.blocks('gtceu:cupronickel_coil_block'))
    .where('P', Predicates.blocks('gtceu:steel_frame'))
    .where('I', Predicates.blocks('gtceu:bronze_frame'))
    .where('S', Predicates.blocks('gtceu:firebricks')
            .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1)))
    .where('T', Predicates.blocks('gtceu:treated_wood_frame'))
    .where('X', Predicates.controller(Predicates.blocks(definition.get())))
    .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_primitive_bricks", "gtceu:block/machines/alloy_smelter")

    event.create('primitive_cylindrical_hearth', "multiblock")
    .machine((holder) => new $SteamMulti(holder, 4))
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes('primitive_cylindrical_hearth')
    .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
    .pattern(definition => FactoryBlockPattern.start()
    .aisle("ABBBA", "ABBBA", "ABBBA", "ABBBA", "ADEDA", "AADAA", "AAAAA", "AAAAA")
    .aisle("BFBFB", "BFAFB", "BFAFB", "BFAFB", "DBBBD", "AEEEA", "AAEAA", "AAEAA")
    .aisle("BBBBB", "BAAAB", "BAAAB", "BAAAB", "EBABE", "DEAED", "AEAEA", "AEAEA")
    .aisle("BFBFB", "BFAFB", "BFAFB", "BFAFB", "DBBBD", "AEEEA", "AAEAA", "AAEAA")
    .aisle("ABBBA", "GBCBG", "ABBBA", "ABBBA", "ADEDA", "AADAA", "AAAAA", "AAAAA")
    .where("A", Predicates.any())
    .where("B", Predicates.blocks("gtceu:firebricks")
        .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1)))
    .where("C", Predicates.controller(Predicates.blocks(definition.get())))
    .where("D", Predicates.blocks("gtceu:igneous_bronze_frame"))
    .where("E", Predicates.blocks("gtceu:igneous_bronze_casing"))
    .where("F", Predicates.blocks("kubejs:carbonized_log"))
    .where("G", Predicates.blocks("gtceu:bronze_pipe_casing")
        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1)))
    .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_primitive_bricks", "gtceu:block/multiblock/primitive_blast_furnace")

    event.create('primitive_processing_factory', 'multiblock')
    .machine((holder) => new $SteamMulti(holder, 4))
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes('ore_processing_plant')
    .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
    .pattern(definition => FactoryBlockPattern.start()
    .aisle(' AAA ', ' FFF ', ' FFF ', '  F  ', '     ', '     ', '     ')
    .aisle('AFFFA', 'FG GF', 'F   F', ' F F ', ' FFF ', '  F  ', '  B  ')
    .aisle('AFFFA', 'F P F', 'F P F', 'F P F', ' FPF ', ' FPF ', ' B B ')
    .aisle('AFFFA', 'FG GF', 'F   F', ' F F ', ' FFF ', '  F  ', '  B  ')
    .aisle(' AAA ', ' FCF ', ' FFF ', '  F  ', '     ', '     ', '     ')
    .where('C', Predicates.controller(Predicates.blocks(definition.get())))
    .where('F', Predicates.blocks('gtceu:firebricks')
        .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1)))
    .where('P', Predicates.blocks(GTBlocks.CASING_BRONZE_PIPE.get()))
    .where('G', Predicates.blocks(GTBlocks.CASING_BRONZE_GEARBOX.get()))
    .where('A', Predicates.blocks(GTBlocks.FIREBOX_BRONZE.get()))
    .where('B', Predicates.blocks('gtceu:igneous_bronze_casing'))
    .where(' ', Predicates.any())
    .build())
    .workableCasingModel(
            "gtceu:block/casings/solid/machine_primitive_bricks", "gtceu:block/multiblock/primitive_blast_furnace")

    event.create('primitive_coking_array', 'multiblock')
    .machine((holder) => new $SteamMulti(holder, 16))
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes('primitive_coking_array')
    .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
    .pattern(definition => FactoryBlockPattern.start("right", "back", "up")
    .aisle('ABCCCBA', 'BCCCCCB', 'CCCCCCC', 'ECCCCCE', 'CCCCCCC', 'BCCCCCB', 'ABCCCBA')
    .aisle('ABCDCBA', 'BCCACCB', 'CCCCCCC', 'EACCCAE', 'CCCCCCC', 'BCCACCB', 'ABCECBA')
    .aisle('ABCCCBA', 'BCCCCCB', 'CCCCCCC', 'ECCCCCE', 'CCCCCCC', 'BCCCCCB', 'ABCECBA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCECBA', 'ACCACCA', 'AEACAEA', 'ACCACCA', 'ABCECBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACCCAA', 'AACCCAA', 'AACCCAA', 'AAAAAAA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACECAA', 'AAEAEAA', 'AACECAA', 'AAAAAAA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACCCAA', 'AACCCAA', 'AACCCAA', 'AAAAAAA', 'AAAAAAA')
    .where("A", Predicates.any())
    .where("B", Predicates.blocks("kubejs:carbonized_log"))
    .where("C", Predicates.blocks("gtceu:coke_oven_bricks")
        .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1)))
    .where("D", Predicates.controller(Predicates.blocks(definition.get())))
    .where("E", Predicates.blocks("gtceu:coke_oven_bricks")
        .or(Predicates.blocks('gtceu:coke_oven'))
            .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1)))
    .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_coke_bricks", "gtceu:block/multiblock/distillation_tower")

    event.create('primitive_coking_array_1', 'multiblock')
    .machine((holder) => new $SteamMulti(holder, 16))
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes('primitive_coking_array')
    .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
    .pattern(definition => FactoryBlockPattern.start("right", "back", "up")
    .aisle('ABCCCBA', 'BCCCCCB', 'CCCCCCC', 'ECCCCCE', 'CCCCCCC', 'BCCCCCB', 'ABCCCBA')
    .aisle('ABCDCBA', 'BCCACCB', 'CCCCCCC', 'EACCCAE', 'CCCCCCC', 'BCCACCB', 'ABCECBA')
    .aisle('ABCCCBA', 'BCCCCCB', 'CCCCCCC', 'ECCCCCE', 'CCCCCCC', 'BCCCCCB', 'ABCECBA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCECBA', 'ACCACCA', 'AEACAEA', 'ACCACCA', 'ABCECBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCECBA', 'ACCACCA', 'AEACAEA', 'ACCACCA', 'ABCECBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACCCAA', 'AACCCAA', 'AACCCAA', 'AAAAAAA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACECAA', 'AAEAEAA', 'AACECAA', 'AAAAAAA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACCCAA', 'AACCCAA', 'AACCCAA', 'AAAAAAA', 'AAAAAAA')
    .where("A", Predicates.any())
    .where("B", Predicates.blocks("kubejs:carbonized_log"))
    .where("C", Predicates.blocks("gtceu:coke_oven_bricks")
        .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1)))
    .where("D", Predicates.controller(Predicates.blocks(definition.get())))
    .where("E", Predicates.blocks("gtceu:coke_oven_bricks")
        .or(Predicates.blocks('gtceu:coke_oven'))
            .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1)))
    .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_coke_bricks", "gtceu:block/multiblock/distillation_tower")

    event.create('primitive_coking_array_2', 'multiblock')
    .machine((holder) => new $SteamMulti(holder, 16))
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes('primitive_coking_array')
    .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
    .pattern(definition => FactoryBlockPattern.start("right", "back", "up")
    .aisle('ABCCCBA', 'BCCCCCB', 'CCCCCCC', 'ECCCCCE', 'CCCCCCC', 'BCCCCCB', 'ABCCCBA')
    .aisle('ABCDCBA', 'BCCACCB', 'CCCCCCC', 'EACCCAE', 'CCCCCCC', 'BCCACCB', 'ABCECBA')
    .aisle('ABCCCBA', 'BCCCCCB', 'CCCCCCC', 'ECCCCCE', 'CCCCCCC', 'BCCCCCB', 'ABCECBA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCECBA', 'ACCACCA', 'AEACAEA', 'ACCACCA', 'ABCECBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCECBA', 'ACCACCA', 'AEACAEA', 'ACCACCA', 'ABCECBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCECBA', 'ACCACCA', 'AEACAEA', 'ACCACCA', 'ABCECBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACCCAA', 'AACCCAA', 'AACCCAA', 'AAAAAAA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACECAA', 'AAEAEAA', 'AACECAA', 'AAAAAAA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACCCAA', 'AACCCAA', 'AACCCAA', 'AAAAAAA', 'AAAAAAA')
    .where("A", Predicates.any())
    .where("B", Predicates.blocks("kubejs:carbonized_log"))
    .where("C", Predicates.blocks("gtceu:coke_oven_bricks")
        .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1)))
    .where("D", Predicates.controller(Predicates.blocks(definition.get())))
    .where("E", Predicates.blocks("gtceu:coke_oven_bricks")
        .or(Predicates.blocks('gtceu:coke_oven'))
            .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1)))
    .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_coke_bricks", "gtceu:block/multiblock/distillation_tower")

    event.create('primitive_coking_array_3', 'multiblock')
    .machine((holder) => new $SteamMulti(holder, 16))
    .rotationState(RotationState.NON_Y_AXIS)
    .recipeTypes('primitive_coking_array')
    .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
    .pattern(definition => FactoryBlockPattern.start("right", "back", "up")
    .aisle('ABCCCBA', 'BCCCCCB', 'CCCCCCC', 'ECCCCCE', 'CCCCCCC', 'BCCCCCB', 'ABCCCBA')
    .aisle('ABCDCBA', 'BCCACCB', 'CCCCCCC', 'EACCCAE', 'CCCCCCC', 'BCCACCB', 'ABCECBA')
    .aisle('ABCCCBA', 'BCCCCCB', 'CCCCCCC', 'ECCCCCE', 'CCCCCCC', 'BCCCCCB', 'ABCECBA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCECBA', 'ACCACCA', 'AEACAEA', 'ACCACCA', 'ABCECBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCECBA', 'ACCACCA', 'AEACAEA', 'ACCACCA', 'ABCECBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCECBA', 'ACCACCA', 'AEACAEA', 'ACCACCA', 'ABCECBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCECBA', 'ACCACCA', 'AEACAEA', 'ACCACCA', 'ABCECBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'ABCCCBA', 'ACCCCCA', 'ACCCCCA', 'ACCCCCA', 'ABCCCBA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACCCAA', 'AACCCAA', 'AACCCAA', 'AAAAAAA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACECAA', 'AAEAEAA', 'AACECAA', 'AAAAAAA', 'AAAAAAA')
    .aisle('AAAAAAA', 'AAAAAAA', 'AACCCAA', 'AACCCAA', 'AACCCAA', 'AAAAAAA', 'AAAAAAA')
    .where("A", Predicates.any())
    .where("B", Predicates.blocks("kubejs:carbonized_log"))
    .where("C", Predicates.blocks("gtceu:coke_oven_bricks")
        .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1)))
    .where("D", Predicates.controller(Predicates.blocks(definition.get())))
    .where("E", Predicates.blocks("gtceu:coke_oven_bricks")
        .or(Predicates.blocks('gtceu:coke_oven'))
            .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
            .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1)))
    .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_coke_bricks", "gtceu:block/multiblock/distillation_tower")

})