GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('phase_alternator')
    .category('e')
    .setEUIO('in')
    .setMaxIOSize(3, 0, 3, 2)
    .setSlotOverlay(false, false, GuiTextures.FLUID_SLOT)
    .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
    .setSound(GTSoundEntries.CHEMICAL)
 })

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('superphasic_mixer', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .recipeTypes([GTRecipeTypes.get('fluid_heater'), GTRecipeTypes.get('mixer'), GTRecipeTypes.get('phase_alternator')])
        .appearanceBlock(() => Block.getBlock("gtceu:corrosion_proof_casing"))
        .pattern(definition => FactoryBlockPattern.start()
    .aisle("ABAAABA", "ABBCBBA", "ABBCBBA", "ABBCBBA", "ABBCBBA", "ABBCBBA", "ABBCBBA", "ABBCBBA", "ABBCBBA", "AAABAAA")
    .aisle("BAACAAB", "BCCCCCB", "BAACAAB", "BAACAAB", "BAACAAB", "BAACAAB", "BAACAAB", "BAACAAB", "BAACAAB", "ABBBBBA")
    .aisle("AACCCAA", "BCDDACB", "BAADDAB", "BAAAAAB", "BAAAAAB", "BADDAAB", "BAADDAB", "BAAAAAB", "BAAAAAB", "ABCCCBA")
    .aisle("ACCCCCA", "CCEEACC", "CCAEDCC", "CCAEDCC", "CCDEACC", "CCDEACC", "CCAEDCC", "CCAEDCC", "CCDEACC", "BBCBCBB")
    .aisle("AACCCAA", "BCAAACB", "BAAAAAB", "BAADDAB", "BADDAAB", "BAAAAAB", "BAAAAAB", "BAADDAB", "BADDAAB", "ABCBCBA")
    .aisle("BAACAAB", "BCCCCCB", "BAAAAAB", "BAAAAAB", "BAAAAAB", "BAAAAAB", "BAAAAAB", "BAAAAAB", "BAAAAAB", "ABBBCBA")
    .aisle("ABAAABA", "ABCCCBA", "ABBBBBA", "ABBXBBA", "ABBBBBA", "ABBCBBA", "ABBCBBA", "ABBCBBA", "ABBCBBA", "AAABAAA")
        .where("A", Predicates.blocks("minecraft:air"))
        .where("B", Predicates.blocks("gtceu:corrosion_proof_casing")
            .or(Predicates.autoAbilities(definition.getRecipeTypes()))
            .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1)))
        .where("C", Predicates.blocks("gtceu:frostproof_machine_casing"))
        .where("D", Predicates.blocks("gtceu:nichrome_coil_block"))
        .where("E", Predicates.blocks("gtceu:ptfe_pipe_casing"))
        .where("X", Predicates.controller(Predicates.blocks(definition.get())))
        .build())
        .workableCasingModel('gtceu:block/casings/solid/corrosion_proof_casing', 'gtceu:block/machines/fluid_heater')
})
