StartupEvents.registry('block', event => {

    event.create('beryllium_aluminium_alloy_casing')
        .displayName('Beryllium-Aluminium Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/beryllium_aluminium_alloy_casing')

    event.create('birmabright_casing')
        .displayName('Birmabright Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/birmabright_casing')

    event.create('beryllium_bronze_casing')
        .displayName('Beryllium Bronze Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/beryllium_bronze_casing')

    event.create('blue_steel_casing')
        .displayName('Blue Steel Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/blue_steel_casing')

    event.create('duralumin_casing')
        .displayName('Duralumin Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/duralumin_casing')

    event.create('elgiloy_casing')
        .displayName('Elgiloy Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/elgiloy_casing')

    event.create('hydronalium_casing')
        .displayName('Hydronalium Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/hydronalium_casing')

    event.create('kovar_casing')
        .displayName('Kovar Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/kovar_casing')

    event.create('red_steel_casing')
        .displayName('Red Steel Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/red_steel_casing')

    event.create('silicon_bronze_casing')
        .displayName('Silicon Bronze Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/silicon_bronze_casing')

    event.create('sterling_silver_casing')
        .displayName('Sterling Silver Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/sterling_silver_casing')

    event.create('zamak_casing')
        .displayName('Zamak Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/zamak_casing')

    event.create('tumbaga_casing')
        .displayName('Tumbaga Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/tumbaga_casing')

    event.create('silicone_rubber_casing')
        .displayName('Silicone Rubber Casing')
        .hardness(5)
        .resistance(1)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .textureAll('kubejs:block/casings/large_cubes/silicone_rubber_casing')

    event.create('transplatine_casing')
        .displayName('Transplatine Casing')
        .hardness(9)
        .resistance(1.5)
        .soundType('metal')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .textureAll('kubejs:block/casings/large_cubes/transplatine_casing')


})

GTCEuStartupEvents.registry('gtceu:recipe_type', event => {

    // Large Rock Crusher Recipe Type
    event.create('large_rock_crusher')
        .category('large_rock_crusher')
        .setEUIO('in')
        .setMaxIOSize(1, 1, 2, 0)
        .setProgressBar(GuiTextures.PROGRESS_BAR_HAMMER , FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.FORGE_HAMMER)

})


GTCEuStartupEvents.registry('gtceu:machine', event => {

    const largeCube = (type, casing) => {

        event.create(`t_large_${type}`, 'multiblock')
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType(type)
            .recipeModifiers([GTRecipeModifiers.OC_PERFECT])
            .appearanceBlock(() => Block.getBlock(`kubejs:${casing}_casing`))
            .pattern(definition => FactoryBlockPattern.start()
                .aisle('CCC', 'CCC', 'CCC')
                .aisle('CCC', 'C C', 'CCC')
                .aisle('CCC', 'CKC', 'CCC')
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('C', Predicates.blocks(`kubejs:${casing}_casing`).setMinGlobalLimited(5)
                    .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                    .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
                    .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
                    .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                    .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(1)))
                .where(' ', Predicates.air())
                .build())
            .workableCasingModel(`gtceu:block/casings/large_cubes/${casing}_casing`, `gtceu:block/machines/${type}`)

    }



    // Generic Cubes
    largeCube('bender', 'birmabright')
    largeCube('centrifuge', 'tumbaga')
    largeCube('electrolyzer', 'duralumin')
    largeCube('extruder', 'beryllium_aluminium_alloy')
    largeCube('forming_press', 'elgiloy')
    largeCube('lathe', 'beryllium_bronze')
    largeCube('macerator', 'blue_steel')
    largeCube('mixer', 'kovar')
    largeCube('ore_washer', 'hydronalium')
    largeCube('sifter', 'zamak')
    largeCube('thermal_centrifuge', 'silicon_bronze')
    largeCube('wiremill', 'sterling_silver')
    largeCube('autoclave', 'silicone_rubber')
    largeCube('assembler', 'transplatine')


    // Large Rock Crusher
    event.create('large_rock_crusher', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('large_rock_crusher')
        .recipeModifiers([GTRecipeModifiers.OC_PERFECT])
        .appearanceBlock(() => Block.getBlock('kubejs:red_steel_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCC', 'CCC', 'CCC')
            .aisle('CCC', 'C C', 'CCC')
            .aisle('CCC', 'CKC', 'CCC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('C', Predicates.blocks('kubejs:red_steel_casing').setMinGlobalLimited(5)
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(2)))
            .where(' ', Predicates.air())
            .build())
        .workableCasingModel('gtceu:block/casings/large_cubes/red_steel_casing', 'gtceu:block/machines/rock_crusher')

})