#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jul 29 04:18:05 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=4
shaderPack=Hysteria-Shaders-Universal-v1.2.2.zip
enableShaders=false
