#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Aug 21 16:08:34 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=4
shaderPack=superDuperVanilla.zip
enableShaders=false
