ServerEvents.recipes(e => {
    e.remove({output: 'gtceu:nullium_nugget'})
    e.remove({output: 'gtceu:tiny_nullium_dust'})
    e.remove({output: 'gtceu:small_nullium_dust'})
    e.remove({input: 'iron_block', type: 'ae2:inscriber'})

    e.remove({input: 'gtceu:fine_copper_wire', type: 'crafting_shaped'})
    e.remove({input: 'gtceu:nullium_nugget'})
    e.remove({input: 'gtceu:tiny_nullium_dust'})
    e.remove({input: 'gtceu:small_nullium_dust'})
    e.remove({input: '#notreepunching:saws'})
    e.remove({not: {mod: 'gtceu'}, output: 'gtceu:andesite_alloy_ingot'})

    e.remove({id: 'create:item_application/andesite_casing_from_log'})
    e.remove({id: 'create:item_application/andesite_casing_from_wood'})
    e.remove({id: 'create:item_application/brass_casing_from_log'})
    e.remove({id: 'create:item_application/brass_casing_from_wood'})
    e.remove({id: 'create:item_application/copper_casing_from_log'})
    e.remove({id: 'create:item_application/copper_casing_from_wood'})
    e.remove({id: 'create:mixing/brass_ingot'})
    e.remove({id: 'create:crafting/materials/andesite_alloy_block'})

    e.remove({id: 'gtceu:shaped/basic_circuit_board'})
    e.remove({id: 'gtceu:electrolyzer/decomposition_electrolyzing_echoite'})
    e.remove({id: 'gtceu:electrolyzer/decomposition_electrolyzing_tainted_calcite_concentrate'})

    e.remove({id: 'minecraft:furnace'})
    e.remove({id: 'minecraft:crafting_table'})
    e.remove({id: 'quark:building/crafting/furnaces/blackstone_furnace'})
    e.remove({id: 'quark:building/crafting/furnaces/deepslate_furnace'})
    e.remove({id: 'quark:building/crafting/furnaces/cobblestone_furnace'})
    e.remove({id: 'quark:building/crafting/furnaces/mixed_furnace'})

    e.remove({id: 'notreepunching:flint_knife'})
    e.remove({id: 'notreepunching:iron_knife'})
    e.remove({id: 'notreepunching:gold_knife'})
    e.remove({id: 'notreepunching:diamond_knife'})
    e.remove({id: 'notreepunching:netherite_knife'})

    e.remove({id: 'gtceu:shaped/axe_flint'})
    e.remove({id: 'gtceu:shaped/pickaxe_flint'})
    e.remove({id: 'gtceu:shaped/shovel_flint'})
    e.remove({id: 'gtceu:shaped/hoe_flint'})
    e.remove({id: 'gtceu:mixer/energium_dust'})

    e.remove({id: 'ars_nouveau:source_gem_block'})
    e.remove({id: 'ars_nouveau:source_gem_block_2'})
    e.remove({id: 'botania:mana_ring'})

    e.remove({output: /gtceu:.*_solar_panel/})
    e.remove({id: 'minecraft:ancient_debris'})
    e.remove({mod: /(ad_astra|ad_astra_giselle_addon|create|)/, input: /ad_astra:.*(iron|steel|desh|ostrum|calorite)_.*/})
    e.remove({mod: /(ad_astra|ad_astra_giselle_addon|create|)/, output: /ad_astra:.*(iron|steel|desh|ostrum|calorite)_.*/})

    e.remove({type: 'crafting_shaped', output: /ad_astra:(steel|desh|ostrum|calorite)_(engine|tank)/})


    e.remove({output: /(ae2|megacells):(spatial_)?cell_component_.*/})
    e.remove({output: /(?!gtceu).*:(.*_)?(cell|disk)_housing/})
    e.remove({output: /(?!gtceu).*:(.*_)?(cell|disk)_(drive_)?.*/})
    e.remove({id: 'ae2:network/crafting/molecular_assembler'})
    e.remove({id: 'ae2:network/blocks/interfaces_interface'})
    e.remove({id: 'ae2:network/blocks/pattern_providers_interface'})
    e.remove({output: /ae2:(inscriber|charger)/})
    e.remove({id: 'advanced_ae:quantum_alloy'})
    e.remove({id: 'advanced_ae:quantum_alloy_plate'})
    e.remove({id: 'advanced_ae:quantum_storage_component'})
    e.remove({id: 'advanced_ae:quantum_processor_print_eae'})
    e.remove({id: 'advanced_ae:quantum_processor_chamber'})
    e.remove({id: 'advanced_ae:quantum_infusion'})
    e.remove({mod: 'ae2', output: /ae2:.*_(smart|covered|glass|covered_dense|smart_dense)_cable/})
    e.remove({mod: 'minecraft', output: /avaritia:(infinity|neutronium|neutron)_.*/})
    e.remove({mod: 'avaritia'})
    e.remove({type: 'ae2:inscriber'})
    e.remove({type: 'ae2:charger'})
    e.remove({id: /gtceu:forming_press\/ae2_processor_.*_print(2)?/})
    e.remove({id: 'arseng:mega_source_cell_housing'})
    e.remove({id: 'arseng:source_cell_housing'})
    e.remove({id: /arseng:source_storage_cell_.*/})
    e.remove({id: /ae2:network\/cells\/.*_storage_cell_.*_storage/})
    e.remove({id: /ae2:network\/cells\/.*_storage_cell_.*/})
    e.remove({id: /ae2:network\/crafting\/.*_cpu_crafting_storage/})
    e.remove({id: /ae2:network\/cells\/.*_cell_housing/})

    e.remove({id: 'ae2things:cells/disk_housing'})
    e.remove({id: 'ae2:network/crafting/cpu_crafting_monitor'})
    e.remove({id: 'ae2:network/crafting/cpu_crafting_accelerator'})
    e.remove({id: /gtceu:assembler\/ae2_processor_.*/})
    e.remove({id: /ae2things:cells\/disk_drive_.*(_storage)?/})

    e.remove({id: 'undergarden:catalyst'})
    e.remove({output: 'botania:manasteel_ingot'})
    e.remove({output: 'botania:manasteel_nugget'})

    e.remove({id: 'advanced_ae:reactionchamber'})
    e.remove({id: 'minecraft:netherite_ingot'})
    e.remove({id: 'gtceu:smelting/smelt_dust_netherite_to_ingot'})
})