ServerEvents.recipes(event => {
    const GTM = event.recipes.gtceu
GTM.chemical_vat('vaelthorite_sulfuric_leach')
    .itemInputs('4x gtceu:vaelthorite_dust')
    .inputFluids('gtceu:sulfuric_acid 2000', 'gtceu:steam 1000')
    .outputFluids('gtceu:vaelthorium_sulfate_solution 3000', 'gtceu:hydrogen_sulfide 500')
    .duration(300)
    .addData('HeatPressure', 6.0)
    .addData('Temp', 800)
    .EUt(8192)

GTM.chemical_reactor('vaelthorite_gem_recovery')
    .inputFluids('gtceu:vaelthorium_sulfate_solution 3000', 'gtceu:hydrogen 2000')
    .itemOutputs('3x gtceu:vaelthorium_dust', '2x gtceu:lead_dust')
    .outputFluids('gtceu:diluted_sulfuric_acid 1000')
    .duration(400)
    .EUt(8192)

GTM.centrifuge('vaelthorite_trace_separation')
    .inputFluids('gtceu:diluted_sulfuric_acid 1000')
    .itemOutputs('2x gtceu:sulfur_dust', 'gtceu:molybdenum_dust', 'gtceu:vanadium_dust')
    .duration(220)
    .EUt(8192)


GTM.large_chemical_reactor('sulvarite_aqua_regia_leach')
    .itemInputs('4x gtceu:sulvarite_dust')
    .inputFluids('gtceu:aqua_regia 3000')
    .outputFluids('gtceu:sulvarite_leachate 3000', 'gtceu:nitric_oxide 500')
    .duration(320)
    .addData('HeatPressure', 5.0)
    .addData('Temp', 700)
    .EUt(8192)

GTM.chemical_reactor('sulvarite_precious_recovery')
    .inputFluids('gtceu:sulvarite_leachate 3000', 'gtceu:hydrogen 1500')
    .itemOutputs('3x gtceu:sulvarium_dust', '2x gtceu:gold_dust', '2x gtceu:silver_dust', 'gtceu:bismuth_dust')
    .duration(420)
    .EUt(16384)


GTM.chemical_vat('kethrenite_ammonia_leach')
    .itemInputs('4x gtceu:kethrenite_dust')
    .inputFluids('gtceu:ammonia 2000', 'gtceu:oxygen 1000')
    .outputFluids('gtceu:kethrenite_ammine_solution 3000')
    .duration(360)
    .addData('HeatPressure', 7.0)
    .addData('Temp', 900)
    .EUt(8192)

GTM.electrolyzer('kethrenite_gem_recovery')
    .inputFluids('gtceu:kethrenite_ammine_solution 3000')
    .itemOutputs('3x gtceu:kethrite_dust', '2x gtceu:copper_dust', '2x gtceu:nickel_dust', 'gtceu:cobalt_dust')
    .duration(400)
    .EUt(16384)


GTM.chemical_vat('vorrexinite_chlorination')
    .itemInputs('4x gtceu:vorrexinite_dust')
    .inputFluids('gtceu:chlorine 3000', 'gtceu:oxygen 1000')
    .outputFluids('gtceu:pgm_chloride_solution 3000')
    .duration(400)
    .addData('HeatPressure', 8.0)
    .addData('Temp', 1100)
    .EUt(16384)

GTM.large_chemical_reactor('vorrexinite_pgm_separation')
    .inputFluids('gtceu:pgm_chloride_solution 3000', 'gtceu:ammonium_chloride 1000')
    .itemOutputs('3x gtceu:vorrexite_dust', '2x gtceu:osmium_dust', '2x gtceu:iridium_dust', 'gtceu:ruthenium_dust')
    .duration(480)
    .EUt(16384)


GTM.chemical_vat('thermastone_oxidative_leach')
    .itemInputs('8x gtceu:thermastone_dust')
    .inputFluids('gtceu:oxygen 2000', 'gtceu:chlorine 1000')
    .outputFluids('gtceu:thermavyte_oxide 3000')
    .duration(350)
    .addData('HeatPressure', 9.0)
    .addData('Temp', 1400)
    .EUt(16384)

GTM.electrolyzer('thermastone_gem_recovery')
    .inputFluids('gtceu:thermavyte_oxide 3000')
    .itemOutputs('3x gtceu:thermavyte_dust', '2x gtceu:titanium_dust', 'gtceu:vanadium_dust', '2x gtceu:chromium_dust')
    .duration(320)
    .EUt(16384)


GTM.chemical_vat('cindrax_alkaline_fusion')
    .itemInputs('4x gtceu:cindrax_dust', '2x gtceu:sodium_hydroxide_dust')
    .inputFluids('gtceu:steam 1000')
    .outputFluids('gtceu:cindrax_alkaline_melt 3000')
    .duration(280)
    .addData('HeatPressure', 5.0)
    .addData('Temp', 900)
    .EUt(8192)

GTM.chemical_reactor('cindrax_gem_recovery')
    .inputFluids('gtceu:cindrax_alkaline_melt 3000', 'gtceu:hydrochloric_acid 1000')
    .itemOutputs('3x gtceu:cindralite_dust', '2x gtceu:silicon_dust', '2x gtceu:tin_dust', 'gtceu:gallium_dust')
    .duration(360)
    .EUt(16384)


GTM.chemical_vat('aetheric_palladite_pressure_leach')
    .itemInputs('4x gtceu:aetheric_palladite_dust')
    .inputFluids('gtceu:sulfuric_acid 2000', 'gtceu:oxygen 1000')
    .outputFluids('gtceu:palladite_leachate 1000', 'gtceu:aetherite_residue 750')
    .duration(400)
    .addData('HeatPressure', 8.0)
    .addData('Temp', 1200)
    .EUt(16384)

GTM.large_chemical_reactor('aetheric_palladite_recovery')
    .inputFluids('gtceu:palladite_leachate 2000', 'gtceu:ammonium_chloride 500')
    .itemOutputs('6x gtceu:aetherite_dust', '4x gtceu:palladium_dust', '2x gtceu:niobium_dust')
    .outputFluids('gtceu:rhodium 216')
    .duration(440)
    .EUt(16384)

GTM.centrifuge('aetherite_residue_recovery')
    .inputFluids('gtceu:aetherite_residue 1500')
    .itemOutputs('gtceu:aetherite_dust', 'gtceu:hafnium_dust', 'gtceu:sulfur_dust')
    .duration(440)
    .EUt(16384)

GTM.chemical_vat('pyrathite_fluoride_processing')
    .itemInputs('4x gtceu:pyrathite_dust')
    .inputFluids('gtceu:hydrofluoric_acid 2000', 'gtceu:oxygen 1000')
    .outputFluids('gtceu:pyrathite_fluoride_vapor 2500')
    .duration(360)
    .addData('HeatPressure', 10.0)
    .addData('Temp', 1600)
    .EUt(16384)

GTM.electrolyzer('pyrathite_gem_recovery')
    .inputFluids('gtceu:pyrathite_fluoride_vapor 2500')
    .itemOutputs('3x gtceu:pyrathene_dust', '2x gtceu:titanium_dust', '2x gtceu:vanadium_dust', 'gtceu:tungsten_dust', 'gtceu:molybdenum_dust')
    .duration(420)
    .EUt(16384)

GTM.chemical_vat('nulledryte_temporal_stabilization')
    .itemInputs('4x gtceu:nulledryte_dust')
    .inputFluids('gtceu:xenon 1000', 'gtceu:distilled_water 1000')
    .itemOutputs('4x gtceu:chronosite_dust')
    .outputFluids('gtceu:unstable_oganesson_solution 1000')
    .duration(600)
    .addData('HeatPressure', 13.0)
    .addData('Temp', 3000)
    .EUt(32768)

GTM.chemical_vat('nulledryte_decay_capture')
    .inputFluids('gtceu:unstable_oganesson_solution 1000', 'gtceu:hypothermic_helium_3_plasma 2000')
    .outputFluids('gtceu:cryostabilized_decay_matrix 1000')
    .duration(800)
    .addData('HeatPressure', 14.0)
    .addData('Temp', 3500)
    .EUt(32768)

GTM.centrifuge('nulledryte_isotope_separation')
    .inputFluids('gtceu:cryostabilized_decay_matrix 1000')
    .itemOutputs('2x gtceu:oganesson_dust', '2x gtceu:darmstadtium_dust')
    .duration(400)
    .EUt(32768)


GTM.chemical_vat('xycrhovite_resonance_extraction')
    .itemInputs('4x gtceu:xycrhovite_dust')
    .inputFluids('gtceu:refined_sentience 200', 'gtceu:resonance_plasma 100')
    .outputFluids('gtceu:xycrhovite_resonance_solution 2000', 'gtceu:echo_fluid 500')
    .duration(500)
    .addData('HeatPressure', 11.0)
    .addData('Temp', 2000)
    .EUt(16384)

GTM.electrolyzer('xycrhovite_main_products_recovery')
    .inputFluids('gtceu:xycrhovite_resonance_solution 2000')
    .itemOutputs('4x gtceu:draconium_dust', '3x gtceu:dilithium_dust')
    .duration(400)
    .EUt(32768)

GTM.fluid_solidifier('xycrhovite_echo_crystallization')
    .inputFluids('gtceu:echo_fluid 500')
    .itemOutputs('4x gtceu:echo_dust')
    .duration(200)
    .EUt(16384)


GTM.chemical_vat('vheszcryl_supercritical_extraction')
    .itemInputs('4x gtceu:vheszcryl_dust')
    .inputFluids('gtceu:carbon_dioxide 2000', 'gtceu:hydrofluoric_acid 500')
    .outputFluids('gtceu:vheszcryl_extract 2000', 'gtceu:transcendentine_solution 500')
    .duration(480)
    .addData('HeatPressure', 12.0)
    .addData('Temp', 2500)
    .EUt(32768)

GTM.chemical_reactor('vheszcryl_gem_precipitation')
    .inputFluids('gtceu:vheszcryl_extract 2000', 'gtceu:ammonia 500')
    .itemOutputs('5x gtceu:vhaelcryite_dust')
    .duration(360)
    .EUt(16384)

GTM.electrolyzer('vheszcryl_transcendentine_recovery')
    .inputFluids('gtceu:transcendentine_solution 500')
    .itemOutputs('3x gtceu:transcendentine_dust')
    .duration(200)
    .EUt(32768)


GTM.chemical_vat('grothemite_acid_cracking')
    .itemInputs('4x gtceu:grothemite_dust')
    .inputFluids('gtceu:sulfuric_acid 2000', 'gtceu:hydrogen_peroxide 500')
    .outputFluids('gtceu:grothemite_leachate 3000')
    .itemOutputs('2x gtceu:iron_dust')
    .duration(400)
    .addData('HeatPressure', 10.0)
    .addData('Temp', 1800)
    .EUt(16384)

GTM.centrifuge('grothemite_material_separation')
    .inputFluids('gtceu:grothemite_leachate 3000')
    .itemOutputs('3x gtceu:rare_earth_dust', '2x gtceu:hafnium_dust', 'gtceu:potassium_dust')
    .outputFluids('gtceu:iron_sulfate_solution 500')
    .duration(360)
    .EUt(16384)

GTM.electrolyzer('grothemite_iron_recovery')
    .inputFluids('gtceu:iron_sulfate_solution 500')
    .itemOutputs('gtceu:pyrite_dust')
    .outputFluids('gtceu:sulfuric_acid 300')
    .duration(200)
    .EUt(8192)


GTM.chemical_vat('krethavine_chloride_process')
    .itemInputs('4x gtceu:krethavine_dust', '2x gtceu:carbon_dust')
    .inputFluids('gtceu:chlorine 3000')
    .outputFluids('gtceu:krethavine_tetrachloride 2000', 'gtceu:lanthanum_chloride_solution 500')
    .duration(440)
    .addData('HeatPressure', 11.0)
    .addData('Temp', 2200)
    .EUt(16384)

GTM.chemical_reactor('krethavine_kraethite_recovery')
    .inputFluids('gtceu:krethavine_tetrachloride 2000')
    .itemInputs('2x gtceu:magnesium_dust')
    .itemOutputs('4x gtceu:kraethite_dust', '3x gtceu:titanium_dust', 'gtceu:zirconium_dust')
    .outputFluids('gtceu:magnesium_chloride_solution 1000')
    .duration(480)
    .EUt(16384)

GTM.electrolyzer('krethavine_lanthanum_recovery')
    .inputFluids('gtceu:lanthanum_chloride_solution 1000')
    .itemOutputs('3x gtceu:lanthanum_dust')
    .outputFluids('gtceu:chlorine 1500')
    .duration(200)
    .EUt(16384)


GTM.chemical_vat('orvexite_nitric_dissolution')
    .itemInputs('4x gtceu:orvexite_dust')
    .inputFluids('gtceu:nitric_acid 3000', 'gtceu:hydrofluoric_hydroxicide 500')
    .outputFluids('gtceu:orvexite_nitrate_solution 3000', 'gtceu:plutonium_nitrate_solution 500')
    .duration(500)
    .addData('HeatPressure', 12.0)
    .addData('Temp', 2500)
    .EUt(32768)

GTM.large_chemical_reactor('orvexite_pgm_recovery')
    .inputFluids('gtceu:orvexite_nitrate_solution 3000', 'gtceu:ammonium_chloride 500')
    .itemOutputs('3x gtceu:osmiridium_dust', '2x gtceu:rhodium_dust', '2x gtceu:rare_earth_dust')
    .duration(440)
    .EUt(32768)

GTM.chemical_reactor('orvexite_plutonium_reduction')
    .inputFluids('gtceu:plutonium_nitrate_solution 500', 'gtceu:hydrogen 1000')
    .itemOutputs('3x gtceu:plutonium_dust')
    .outputFluids('gtceu:nitric_acid 250')
    .duration(300)
    .EUt(32768)


GTM.chemical_vat('phazdurite_feed_preparation')
    .itemInputs('4x gtceu:phazdurite_dust')
    .inputFluids('gtceu:nitric_acid 3000', 'gtceu:hydrogen_peroxide 500')
    .outputFluids('gtceu:phazdurite_feed_solution 4000', 'gtceu:radon 500')
    .duration(500)
    .addData('HeatPressure', 14.0)
    .addData('Temp', 3500)
    .EUt(32768)

GTM.chemical_reactor('phazdurite_feed_adjusting')
    .inputFluids('gtceu:phazdurite_feed_solution 4000', 'gtceu:nitric_acid 1000')
    .outputFluids('gtceu:adjusted_phazdurite_feed 5000')
    .duration(300)
    .EUt(16384)

GTM.extraction_column('phazdurite_purex_extraction')
    .inputFluids('gtceu:adjusted_phazdurite_feed 5000', 'gtceu:tbp_solution 5000')
    .outputFluids('gtceu:phazdurite_organic_phase 3000', 'gtceu:phazdurite_raffinate 7000')
    .duration(600)
    .EUt(16384)

GTM.scrubbing_column('phazdurite_purex_scrubbing')
    .inputFluids('gtceu:phazdurite_organic_phase 3000', 'gtceu:dilute_nitric_acid 1000')
    .outputFluids('gtceu:phazdurite_scrubbed_phase 3000', 'gtceu:phazdurite_scrub_waste 1000')
    .duration(400)
    .EUt(16384)

GTM.partition_column('phazdurite_actinide_partition')
    .inputFluids('gtceu:phazdurite_scrubbed_phase 3000', 'gtceu:hydroxylamine_nitrate 500')
    .outputFluids('gtceu:transcendentine_solution 500', 'gtceu:organic_naquadria_phase 2000')
    .duration(800)
    .EUt(16384)

GTM.electrolyzer('phazdurite_transcendentine_recovery')
    .inputFluids('gtceu:transcendentine_solution 500')
    .itemOutputs('3x gtceu:transcendentine_dust')
    .duration(250)
    .EUt(32768)

GTM.stripping_column('phazdurite_naquadria_stripping')
    .inputFluids('gtceu:organic_naquadria_phase 2000', 'gtceu:dilute_nitric_acid 1000')
    .outputFluids('gtceu:naquadria_nitrate_solution 2000', 'gtceu:spent_tbp 1000')
    .duration(500)
    .EUt(16384)

GTM.chemical_reactor('phazdurite_naquadria_precipitation')
    .inputFluids('gtceu:naquadria_nitrate_solution 2000', 'gtceu:ammonia 500')
    .itemOutputs('4x gtceu:naquadria_dust')
    .duration(300)
    .EUt(32768)
})