//please send some supporp for my handz
ServerEvents.recipes(biomanced => {
const GTM = biomanced.recipes.gtceu

GTM.organism_incubation_chamber('axolotl_biomancy_simulation')
    .notConsumable('minecraft:axolotl_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .chancedOutput('biomancy:mob_sinew', 7500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('bat_biomancy_simulation')
    .notConsumable('minecraft:bat_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .chancedOutput('biomancy:mob_fang', 5000, 0)
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_claw', 6000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('bee_biomancy_simulation')
    .notConsumable('minecraft:bee_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .chancedOutput('biomancy:mob_sinew', 5000, 0)
    .chancedOutput('biomancy:toxin_gland', 3333, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('blaze_biomancy_simulation')
    .notConsumable('minecraft:blaze_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('2x biomancy:volatile_gland')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('camel_biomancy_simulation')
    .notConsumable('minecraft:camel_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('3x biomancy:mob_sinew')
    .itemOutputs('1x biomancy:mob_gland')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('cat_biomancy_simulation')
    .notConsumable('minecraft:cat_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_claw')
    .chancedOutput('biomancy:mob_fang', 3000, 0)
    .chancedOutput('biomancy:mob_sinew', 6500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('cave_spider_biomancy_simulation')
    .notConsumable('minecraft:cave_spider_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .chancedOutput('biomancy:mob_sinew', 5000, 0)
    .chancedOutput('biomancy:toxin_gland', 3333, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('chicken_biomancy_simulation')
    .notConsumable('minecraft:chicken_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .chancedOutput('biomancy:mob_sinew', 7500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('cod_biomancy_simulation')
    .notConsumable('minecraft:cod_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .chancedOutput('biomancy:mob_sinew', 6500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('cow_biomancy_simulation')
    .notConsumable('minecraft:cow_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_gland', 7000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('creeper_biomancy_simulation')
    .notConsumable('minecraft:creeper_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('2x biomancy:volatile_gland')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('dolphin_biomancy_simulation')
    .notConsumable('minecraft:dolphin_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('donkey_biomancy_simulation')
    .notConsumable('minecraft:donkey_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('drowned_biomancy_simulation')
    .notConsumable('minecraft:drowned_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('elder_guardian_biomancy_simulation')
    .notConsumable('minecraft:elder_guardian_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('3x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_gland', 7500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('enderman_biomancy_simulation')
    .notConsumable('minecraft:enderman_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('2x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 5000, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('endermite_biomancy_simulation')
    .notConsumable('minecraft:endermite_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 5000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('evoker_biomancy_simulation')
    .notConsumable('minecraft:evoker_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('2x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 5000, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('fox_biomancy_simulation')
    .notConsumable('minecraft:fox_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_claw')
    .chancedOutput('biomancy:mob_fang', 3000, 0)
    .chancedOutput('biomancy:mob_sinew', 6500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('frog_biomancy_simulation')
    .notConsumable('minecraft:frog_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('ghast_biomancy_simulation')
    .notConsumable('minecraft:ghast_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('8x biomancy:volatile_gland')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('glow_squid_biomancy_simulation')
    .notConsumable('minecraft:glow_squid_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('goat_biomancy_simulation')
    .notConsumable('minecraft:goat_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('guardian_biomancy_simulation')
    .notConsumable('minecraft:guardian_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('hoglin_biomancy_simulation')
    .notConsumable('minecraft:hoglin_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('3x biomancy:mob_fang')
    .chancedOutput('biomancy:mob_sinew', 3000, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('horse_biomancy_simulation')
    .notConsumable('minecraft:horse_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('llama_biomancy_simulation')
    .notConsumable('minecraft:llama_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('mooshroom_biomancy_simulation')
    .notConsumable('minecraft:mooshroom_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('mule_biomancy_simulation')
    .notConsumable('minecraft:mule_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('ocelot_biomancy_simulation')
    .notConsumable('minecraft:ocelot_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_claw')
    .chancedOutput('biomancy:mob_fang', 3000, 0)
    .chancedOutput('biomancy:mob_sinew', 6500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('panda_biomancy_simulation')
    .notConsumable('minecraft:panda_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('3x biomancy:mob_fang')
    .itemOutputs('1x biomancy:mob_claw')
    .chancedOutput('biomancy:mob_sinew', 6500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('parrot_biomancy_simulation')
    .notConsumable('minecraft:parrot_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_claw')
    .chancedOutput('biomancy:mob_sinew', 8500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('pig_biomancy_simulation')
    .notConsumable('minecraft:pig_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('piglin_biomancy_simulation')
    .notConsumable('minecraft:piglin_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('piglin_brute_biomancy_simulation')
    .notConsumable('minecraft:piglin_brute_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('pillager_biomancy_simulation')
    .notConsumable('minecraft:pillager_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('polar_bear_biomancy_simulation')
    .notConsumable('minecraft:polar_bear_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_claw')
    .chancedOutput('biomancy:mob_fang', 3000, 0)
    .chancedOutput('biomancy:mob_sinew', 6500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('pufferfish_biomancy_simulation')
    .notConsumable('minecraft:pufferfish_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .chancedOutput('biomancy:mob_sinew', 5000, 0)
    .chancedOutput('biomancy:toxin_gland', 3333, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('rabbit_biomancy_simulation')
    .notConsumable('minecraft:rabbit_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('ravager_biomancy_simulation')
    .notConsumable('minecraft:ravager_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('2x biomancy:mob_sinew')
    .itemOutputs('1x biomancy:mob_claw')
    .chancedOutput('biomancy:mob_sinew', 5000, 0)
    .chancedOutput('biomancy:mob_gland', 8000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('salmon_biomancy_simulation')
    .notConsumable('minecraft:salmon_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .chancedOutput('biomancy:mob_sinew', 6500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('sheep_biomancy_simulation')
    .notConsumable('minecraft:sheep_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('silverfish_biomancy_simulation')
    .notConsumable('minecraft:silverfish_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('skeleton_biomancy_simulation')
    .notConsumable('minecraft:skeleton_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('3x biomancy:mob_marrow')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('skeleton_horse_biomancy_simulation')
    .notConsumable('minecraft:skeleton_horse_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('3x biomancy:mob_marrow')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('sniffer_biomancy_simulation')
    .notConsumable('minecraft:sniffer_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('spider_biomancy_simulation')
    .notConsumable('minecraft:spider_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('squid_biomancy_simulation')
    .notConsumable('minecraft:squid_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('stray_biomancy_simulation')
    .notConsumable('minecraft:stray_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('3x biomancy:mob_marrow')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('strider_biomancy_simulation')
    .notConsumable('minecraft:strider_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('3x biomancy:mob_sinew')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('tropical_fish_biomancy_simulation')
    .notConsumable('minecraft:tropical_fish_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .chancedOutput('biomancy:mob_sinew', 6500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('turtle_biomancy_simulation')
    .notConsumable('minecraft:turtle_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('villager_biomancy_simulation')
    .notConsumable('minecraft:villager_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('vindicator_biomancy_simulation')
    .notConsumable('minecraft:vindicator_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('warden_biomancy_simulation')
    .notConsumable('minecraft:warden_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('4x biomancy:mob_marrow')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('witch_biomancy_simulation')
    .notConsumable('minecraft:witch_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('wither_skeleton_biomancy_simulation')
    .notConsumable('minecraft:wither_skeleton_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('3x biomancy:withered_mob_marrow')
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('wolf_biomancy_simulation')
    .notConsumable('minecraft:wolf_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('zoglin_biomancy_simulation')
    .notConsumable('minecraft:zoglin_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .itemOutputs('3x biomancy:mob_fang')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .duration(200)
    .EUt(480)

GTM.organism_incubation_chamber('zombified_piglin_biomancy_simulation')
    .notConsumable('minecraft:zombified_piglin_spawn_egg')
    .notConsumable('biomancy:despoil_sickle')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 100')
    .perTick(false)
    .itemOutputs('1x biomancy:mob_sinew')
    .chancedOutput('biomancy:mob_sinew', 2500, 0)
    .chancedOutput('biomancy:mob_gland', 1000, 0)
    .duration(200)
    .EUt(480)

    GTM.organism_incubation_chamber('allay_vanilla_simulation')
    .notConsumable('minecraft:allay_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:glowstone_dust')
    .chancedOutput('minecraft:glowstone_dust', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('axolotl_vanilla_simulation')
    .notConsumable('minecraft:axolotl_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:tropical_fish')
    .chancedOutput('minecraft:tropical_fish', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('blaze_vanilla_simulation')
    .notConsumable('minecraft:blaze_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:blaze_rod')
    .chancedOutput('minecraft:blaze_rod', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('cave_spider_vanilla_simulation')
    .notConsumable('minecraft:cave_spider_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:string')
    .itemOutputs('1x minecraft:spider_eye')
    .chancedOutput('minecraft:string', 2500, 0)
    .chancedOutput('minecraft:spider_eye', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('chicken_vanilla_simulation')
    .notConsumable('minecraft:chicken_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:feather')
    .itemOutputs('1x minecraft:chicken')
    .chancedOutput('minecraft:feather', 2500, 0)
    .chancedOutput('minecraft:chicken', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('cod_vanilla_simulation')
    .notConsumable('minecraft:cod_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:cod')
    .itemOutputs('1x minecraft:bone_meal')
    .chancedOutput('minecraft:cod', 2500, 0)
    .chancedOutput('minecraft:bone_meal', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('cow_vanilla_simulation')
    .notConsumable('minecraft:cow_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:leather')
    .itemOutputs('1x minecraft:beef')
    .chancedOutput('minecraft:leather', 2500, 0)
    .chancedOutput('minecraft:beef', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('creeper_vanilla_simulation')
    .notConsumable('minecraft:creeper_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:gunpowder')
    .chancedOutput('minecraft:gunpowder', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('dolphin_vanilla_simulation')
    .notConsumable('minecraft:dolphin_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:cod')
    .chancedOutput('minecraft:cod', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('donkey_vanilla_simulation')
    .notConsumable('minecraft:donkey_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:leather')
    .chancedOutput('minecraft:leather', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('drowned_vanilla_simulation')
    .notConsumable('minecraft:drowned_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:rotten_flesh')
    .itemOutputs('1x minecraft:copper_ingot')
    .itemOutputs('1x minecraft:gold_ingot')
    .chancedOutput('minecraft:rotten_flesh', 2500, 0)
    .chancedOutput('minecraft:copper_ingot', 2500, 0)
    .chancedOutput('minecraft:gold_ingot', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('elder_guardian_vanilla_simulation')
    .notConsumable('minecraft:elder_guardian_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:prismarine_shard')
    .itemOutputs('1x minecraft:prismarine_crystals')
    .itemOutputs('1x minecraft:cod')
    .itemOutputs('1x minecraft:sponge')
    .chancedOutput('minecraft:prismarine_shard', 2500, 0)
    .chancedOutput('minecraft:prismarine_crystals', 2500, 0)
    .chancedOutput('minecraft:cod', 2500, 0)
    .chancedOutput('minecraft:sponge', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('enderman_vanilla_simulation')
    .notConsumable('minecraft:enderman_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:ender_pearl')
    .chancedOutput('minecraft:ender_pearl', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('evoker_vanilla_simulation')
    .notConsumable('minecraft:evoker_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:totem_of_undying')
    .itemOutputs('1x minecraft:emerald')
    .chancedOutput('minecraft:totem_of_undying', 2500, 0)
    .chancedOutput('minecraft:emerald', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('frog_vanilla_simulation')
    .notConsumable('minecraft:frog_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:slime_ball')
    .chancedOutput('minecraft:slime_ball', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('ghast_vanilla_simulation')
    .notConsumable('minecraft:ghast_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:ghast_tear')
    .itemOutputs('1x minecraft:gunpowder')
    .chancedOutput('minecraft:ghast_tear', 2500, 0)
    .chancedOutput('minecraft:gunpowder', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('glow_squid_vanilla_simulation')
    .notConsumable('minecraft:glow_squid_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:glow_ink_sac')
    .chancedOutput('minecraft:glow_ink_sac', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('goat_vanilla_simulation')
    .notConsumable('minecraft:goat_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:goat_horn')
    .chancedOutput('minecraft:goat_horn', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('guardian_vanilla_simulation')
    .notConsumable('minecraft:guardian_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:prismarine_shard')
    .itemOutputs('1x minecraft:prismarine_crystals')
    .itemOutputs('1x minecraft:cod')
    .chancedOutput('minecraft:prismarine_shard', 2500, 0)
    .chancedOutput('minecraft:prismarine_crystals', 2500, 0)
    .chancedOutput('minecraft:cod', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('hoglin_vanilla_simulation')
    .notConsumable('minecraft:hoglin_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:porkchop')
    .itemOutputs('1x minecraft:leather')
    .chancedOutput('minecraft:porkchop', 2500, 0)
    .chancedOutput('minecraft:leather', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('horse_vanilla_simulation')
    .notConsumable('minecraft:horse_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:leather')
    .chancedOutput('minecraft:leather', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('husk_vanilla_simulation')
    .notConsumable('minecraft:husk_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:rotten_flesh')
    .itemOutputs('1x minecraft:iron_ingot')
    .chancedOutput('minecraft:rotten_flesh', 2500, 0)
    .chancedOutput('minecraft:iron_ingot', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('iron_golem_vanilla_simulation')
    .notConsumable('minecraft:iron_golem_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:iron_ingot')
    .itemOutputs('1x minecraft:poppy')
    .chancedOutput('minecraft:iron_ingot', 2500, 0)
    .chancedOutput('minecraft:poppy', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('llama_vanilla_simulation')
    .notConsumable('minecraft:llama_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:leather')
    .chancedOutput('minecraft:leather', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('magma_cube_vanilla_simulation')
    .notConsumable('minecraft:magma_cube_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:magma_cream')
    .chancedOutput('minecraft:magma_cream', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('mooshroom_vanilla_simulation')
    .notConsumable('minecraft:mooshroom_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:leather')
    .itemOutputs('1x minecraft:beef')
    .chancedOutput('minecraft:leather', 2500, 0)
    .chancedOutput('minecraft:beef', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('mule_vanilla_simulation')
    .notConsumable('minecraft:mule_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:leather')
    .chancedOutput('minecraft:leather', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('panda_vanilla_simulation')
    .notConsumable('minecraft:panda_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:bamboo')
    .itemOutputs('1x minecraft:slime_ball')
    .chancedOutput('minecraft:bamboo', 2500, 0)
    .chancedOutput('minecraft:slime_ball', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('parrot_vanilla_simulation')
    .notConsumable('minecraft:parrot_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:feather')
    .chancedOutput('minecraft:feather', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('phantom_vanilla_simulation')
    .notConsumable('minecraft:phantom_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:phantom_membrane')
    .chancedOutput('minecraft:phantom_membrane', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('pig_vanilla_simulation')
    .notConsumable('minecraft:pig_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:porkchop')
    .chancedOutput('minecraft:porkchop', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('piglin_vanilla_simulation')
    .notConsumable('minecraft:piglin_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:gold_ingot')
    .itemOutputs('1x minecraft:gold_nugget')
    .chancedOutput('minecraft:gold_ingot', 2500, 0)
    .chancedOutput('minecraft:gold_nugget', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('piglin_brute_vanilla_simulation')
    .notConsumable('minecraft:piglin_brute_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:gold_ingot')
    .itemOutputs('1x minecraft:gold_nugget')
    .chancedOutput('minecraft:gold_ingot', 2500, 0)
    .chancedOutput('minecraft:gold_nugget', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('pillager_vanilla_simulation')
    .notConsumable('minecraft:pillager_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:arrow')
    .itemOutputs('1x minecraft:emerald')
    .chancedOutput('minecraft:arrow', 2500, 0)
    .chancedOutput('minecraft:emerald', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('polar_bear_vanilla_simulation')
    .notConsumable('minecraft:polar_bear_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:cod')
    .itemOutputs('1x minecraft:salmon')
    .chancedOutput('minecraft:cod', 2500, 0)
    .chancedOutput('minecraft:salmon', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('pufferfish_vanilla_simulation')
    .notConsumable('minecraft:pufferfish_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:pufferfish')
    .itemOutputs('1x minecraft:bone_meal')
    .chancedOutput('minecraft:pufferfish', 2500, 0)
    .chancedOutput('minecraft:bone_meal', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('rabbit_vanilla_simulation')
    .notConsumable('minecraft:rabbit_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:rabbit')
    .itemOutputs('1x minecraft:rabbit_hide')
    .itemOutputs('1x minecraft:rabbit_foot')
    .chancedOutput('minecraft:rabbit', 2500, 0)
    .chancedOutput('minecraft:rabbit_hide', 2500, 0)
    .chancedOutput('minecraft:rabbit_foot', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('ravager_vanilla_simulation')
    .notConsumable('minecraft:ravager_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:saddle')
    .chancedOutput('minecraft:saddle', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('salmon_vanilla_simulation')
    .notConsumable('minecraft:salmon_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:salmon')
    .itemOutputs('1x minecraft:bone_meal')
    .chancedOutput('minecraft:salmon', 2500, 0)
    .chancedOutput('minecraft:bone_meal', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('sheep_vanilla_simulation')
    .notConsumable('minecraft:sheep_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:mutton')
    .itemOutputs('1x minecraft:white_wool')
    .chancedOutput('minecraft:mutton', 2500, 0)
    .chancedOutput('minecraft:white_wool', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('shulker_vanilla_simulation')
    .notConsumable('minecraft:shulker_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:shulker_shell')
    .chancedOutput('minecraft:shulker_shell', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('skeleton_vanilla_simulation')
    .notConsumable('minecraft:skeleton_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:bone')
    .itemOutputs('1x minecraft:arrow')
    .chancedOutput('minecraft:bone', 2500, 0)
    .chancedOutput('minecraft:arrow', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('slime_vanilla_simulation')
    .notConsumable('minecraft:slime_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:slime_ball')
    .chancedOutput('minecraft:slime_ball', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('sniffer_vanilla_simulation')
    .notConsumable('minecraft:sniffer_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:moss_block')
    .chancedOutput('minecraft:moss_block', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('spider_vanilla_simulation')
    .notConsumable('minecraft:spider_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:string')
    .itemOutputs('1x minecraft:spider_eye')
    .chancedOutput('minecraft:string', 2500, 0)
    .chancedOutput('minecraft:spider_eye', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('squid_vanilla_simulation')
    .notConsumable('minecraft:squid_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:ink_sac')
    .chancedOutput('minecraft:ink_sac', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('stray_vanilla_simulation')
    .notConsumable('minecraft:stray_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:bone')
    .itemOutputs('1x minecraft:arrow')
    .chancedOutput('minecraft:bone', 2500, 0)
    .chancedOutput('minecraft:arrow', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('strider_vanilla_simulation')
    .notConsumable('minecraft:strider_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:string')
    .chancedOutput('minecraft:string', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('trader_llama_vanilla_simulation')
    .notConsumable('minecraft:trader_llama_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:leather')
    .chancedOutput('minecraft:leather', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('tropical_fish_vanilla_simulation')
    .notConsumable('minecraft:tropical_fish_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:tropical_fish')
    .itemOutputs('1x minecraft:bone_meal')
    .chancedOutput('minecraft:tropical_fish', 2500, 0)
    .chancedOutput('minecraft:bone_meal', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('turtle_vanilla_simulation')
    .notConsumable('minecraft:turtle_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:seagrass')
    .itemOutputs('1x minecraft:scute')
    .chancedOutput('minecraft:seagrass', 2500, 0)
    .chancedOutput('minecraft:scute', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('vindicator_vanilla_simulation')
    .notConsumable('minecraft:vindicator_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:emerald')
    .chancedOutput('minecraft:emerald', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('warden_vanilla_simulation')
    .notConsumable('minecraft:warden_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:sculk_catalyst')
    .chancedOutput('minecraft:sculk_catalyst', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('witch_vanilla_simulation')
    .notConsumable('minecraft:witch_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:glass_bottle')
    .itemOutputs('1x minecraft:glowstone_dust')
    .itemOutputs('1x minecraft:gunpowder')
    .itemOutputs('1x minecraft:redstone')
    .itemOutputs('1x minecraft:spider_eye')
    .itemOutputs('1x minecraft:sugar')
    .itemOutputs('1x minecraft:stick')
    .chancedOutput('minecraft:glass_bottle', 2500, 0)
    .chancedOutput('minecraft:glowstone_dust', 2500, 0)
    .chancedOutput('minecraft:gunpowder', 2500, 0)
    .chancedOutput('minecraft:redstone', 2500, 0)
    .chancedOutput('minecraft:spider_eye', 2500, 0)
    .chancedOutput('minecraft:sugar', 2500, 0)
    .chancedOutput('minecraft:stick', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('wither_skeleton_vanilla_simulation')
    .notConsumable('minecraft:wither_skeleton_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:coal')
    .itemOutputs('1x minecraft:bone')
    .itemOutputs('1x minecraft:wither_skeleton_skull')
    .chancedOutput('minecraft:coal', 2500, 0)
    .chancedOutput('minecraft:bone', 2500, 0)
    .chancedOutput('minecraft:wither_skeleton_skull', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('zoglin_vanilla_simulation')
    .notConsumable('minecraft:zoglin_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:rotten_flesh')
    .chancedOutput('minecraft:rotten_flesh', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('zombie_vanilla_simulation')
    .notConsumable('minecraft:zombie_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:rotten_flesh')
    .itemOutputs('1x minecraft:iron_ingot')
    .itemOutputs('1x minecraft:carrot')
    .itemOutputs('1x minecraft:potato')
    .chancedOutput('minecraft:rotten_flesh', 2500, 0)
    .chancedOutput('minecraft:iron_ingot', 2500, 0)
    .chancedOutput('minecraft:carrot', 2500, 0)
    .chancedOutput('minecraft:potato', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('zombie_horse_vanilla_simulation')
    .notConsumable('minecraft:zombie_horse_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:rotten_flesh')
    .chancedOutput('minecraft:rotten_flesh', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('zombie_villager_vanilla_simulation')
    .notConsumable('minecraft:zombie_villager_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:rotten_flesh')
    .itemOutputs('1x minecraft:iron_ingot')
    .itemOutputs('1x minecraft:carrot')
    .itemOutputs('1x minecraft:potato')
    .chancedOutput('minecraft:rotten_flesh', 2500, 0)
    .chancedOutput('minecraft:iron_ingot', 2500, 0)
    .chancedOutput('minecraft:carrot', 2500, 0)
    .chancedOutput('minecraft:potato', 2500, 0)
    .duration(100)
    .EUt(240)

GTM.organism_incubation_chamber('zombified_piglin_vanilla_simulation')
    .notConsumable('minecraft:zombified_piglin_spawn_egg')
    .perTick(true)
    .inputFluids('gtceu:artificial_blood 50')
    .perTick(false)
    .itemOutputs('1x minecraft:rotten_flesh')
    .itemOutputs('1x minecraft:gold_nugget')
    .itemOutputs('1x minecraft:gold_ingot')
    .chancedOutput('minecraft:rotten_flesh', 2500, 0)
    .chancedOutput('minecraft:gold_nugget', 2500, 0)
    .chancedOutput('minecraft:gold_ingot', 2500, 0)
    .duration(100)
    .EUt(240)
    
})